### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer when parsing byte data

### ISSUE THREAD

**Issue by jsmartini** [construct/construct#1004]
DF.parse(pkt)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 2653, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/jsmartini/.local/lib/python3.10/site-packages/construct/core.py", line 2411, in _parse
    for i in range(count):
TypeError: 'float' object cannot be interpreted as an integer
type(pkt)
<class 'bytes'>
len(pkt)
67611
DF.sizeof()
67611.0

This never happens on any other script I've written. This is also being done in a multiprocessing pool.

Any help would be great.
Thank you!
The sizing of the byte data and the structure I am using is correct. This works on literally any other code I have except this one script. I am also doing this with multiprocessing pools.

Thank you.

**Comment by arekbulski** [comment]
Please provide what DF and pkt are exactly. So the problem is that sizeof() returns a float, is that it? Have you tried pip upgrading the library?
