### ISSUE TITLE
NullTerminated errors with multibyte terminators

### ISSUE THREAD

**Issue by daxie117** [construct/construct#1046]
Code Snippet:

```py
Sample = Struct(
'field1' / Default(Int32ul, 0xDEADBEEF), 
'greedy' / NullTerminated(GreedyBytes, b'PCIR'), 
'field3' / Default(Int32ul, 0xBEEFDEAD),
)

Sample.build({'greedy': b'some_amt_of_bytes'})
'''
Returns
b'\xef\xbe\xad\xdesome_amt_of_bytesPCIR\xad\xde\xef\xbe'
'''

Sample.parse(b'\xef\xbe\xad\xdesome_amt_of_bytesPCIR\xad\xde\xef\xbe')
ERROR
```

Expected behavior: successful parse returning container with 'field1' = 0xDEADBEEF, 'greedy' = b'some_amt_of_bytes', field3 = 0xBEEFDEAD

Actual behavior: 
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 2653, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 4908, in _parse
    b = stream_read(stream, unit, path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daxie/.local/lib/python3.11/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> greedy
stream read less than specified amount, expected 4, found 1
```

Not sure if this is an actual bug or user error 😅

**Comment by arekbulski** [comment]
I updated the syntax highlight. Please keep it readable. 

At a first glance you seem to have found a bug, yes. I will take some time to investigate this.

**Comment by arekbulski** [comment]
If you look at the source of NullTerminated parsing class, you will notice that it reads "unit (len of term)" bytes at a time. It means the data you write and reread should be a multiple of unit bytes, and the term should start at a boundary. In your example, the read data is not a multiple of 4 and so the class sees basically...

Class source: https://github.com/construct/construct/blob/master/construct/core.py#L5023-L5044
```
"some" (continue) 
"_amt" (continue) 
"_of_" (continue) 
"byte" (continue) 
"sPCI" (continue) 
"R..." (continue)
(and it goes on untill EOF)
```

I will update the documentation and mention this strange behavior explicitly. Thank you for reporting it.
