### ISSUE TITLE
Key Error: Accessing previous element in Array or GreedyRange during parsing.

### ISSUE THREAD

**Issue by mungewell** [construct/construct#1080]
I am trying to access an item in a previous element of array during parsing, so that current element can be `Check()`ed to ensure it's items follow correct sequence.

A simplistic example, gives a 'Key Error' for `Array()` and only parses 1st element for `GreedyRange()` (presumably as 'Key Error' terminates the range).
```
from construct import *

element = Struct(
        "d" / Byte,
        Check(this.d != 0),

        "p" / IfThenElse(this._index == 0,  # I want to reference data in previous element
            Computed(-1),
            Computed(this._.r),             # It seems 'r' does not exist during parsing...
            #Computed(this._.t),            # But 't' does if I reference that instead
        ),
)

end = Struct(
        "b" / Byte,
        "p" / Computed(this._.r),           # can access _AFTER_ GreedyRange/Array is parsed
)

test = Struct(
    "t" / Computed(0),

    #"r" / GreedyRange(element),            # terminates after 1 element
    "r" / Array(3, element),                # gives 'Key Error'

    "e" / end,
)

print(test.parse(b"\x01\x02\03\x00"))
```

```
Traceback (most recent call last):
  File "/home/simon/Accent-Util-github-sdw/test2.py", line 28, in <module>
    print(test.parse(b"\x01\x02\03\x00"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 404, in parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 416, in parse_stream
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2236, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2770, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2530, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2236, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2770, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 3969, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 428, in _parsereport
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/core.py", line 2915, in _parse
  File "/usr/local/lib/python3.11/dist-packages/construct-2.10.70-py3.11.egg/construct/expr.py", line 188, in __call__
KeyError: 'r'
```

Is there any way to access a previous element?

**Comment by arekbulski** [comment]
Does processing on the fly fulfill your needs?
https://construct.readthedocs.io/en/latest/basics.html#processing-on-the-fly
