### ISSUE TITLE
Seek on write failed

### ISSUE THREAD

**Issue by janbrummer** [construct/construct#1081]
Construct fails during write while manipulating a file stream on remote systems for GNOME Secrets. Reason is that those remote filesystem provided through gvfs do not support seek on write, but seek on read only. 

```
  	<pykeepass.pykeepass.PyKeePass object at 0x7f0ca487e390>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 119, in stream_seek
    return stream.seek(offset, whence)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 358, in build_file
    self.build_stream(obj, f, **contextkw)
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 3924, in _build
    return sc._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 3857, in _build
    return sc._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 708, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 3857, in _build
    return sc._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 708, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 3924, in _build
    return sc._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 708, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 708, in _build
    buildret = self.subcon._build(obj2, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2573, in _build
    buildret = self.subcon._build(e, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2144, in _build
    buildret = sc._build(subobj, stream, context, path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 2657, in _build
    return self.subcon._build(obj, stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 4305, in _build
    stream_seek(stream, fallback, 0, path)
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 121, in stream_seek
    raise StreamError("stream.seek() failed, offset %s, whence %s" % (offset, whence), path=path)
construct.core.StreamError: Error in path (building) -> body -> payload -> hmac_hash
stream.seek() failed, offset 3041, whence 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/user/969/gvfs/onedrive:host=d63fd1e1-bdc3-41e6-bab4-23b538901a6d/Meine Dateien/./test.py", line 7, in <module>
    pk.save()
  File "/home/user/Projekte/pykeepass/pykeepass/pykeepass.py", line 183, in save
    raise e
  File "/home/user/Projekte/pykeepass/pykeepass/pykeepass.py", line 173, in save
    KDBX.build_file(
  File "/home/user/.local/lib/python3.12/site-packages/construct/core.py", line 357, in build_file
    with open(filename, 'w+b') as f:
OSError: [Errno 95] Operation not supported

```

**Comment by janbrummer** [comment]
https://gitlab.gnome.org/World/secrets/-/issues/567

**Comment by franzhaas** [comment]
Can it be that this is related to this.: https://github.com/construct/construct/issues/1082? If so, can we close here and continue there? I already proposed a solution there...
