### ISSUE TITLE
Struct can parse buffer but cannot re-build

### ISSUE THREAD

**Issue by OhBonsai** [construct/construct#246]
construct version: 2.8.2
As the title says

```
NumVertices = Bitwise(Aligned(Struct(
    'numVx4' / BitsInteger(4),
    'numVx8' / If(this.numVx4 == 0, BitsInteger(8)),
    'numVx16' / If(this.numVx8 is not None and this.numVx8 == 255, BitsInteger(16)),
), modulus=8))

result = Container(numVx4=0, numVx8=35, numVx16=None)
assert NumVertices.parse(b'\x02\x30') == result
assert NumVertices.build(result) == b'\x02\x30'
```

_Traceback_

```
Traceback (most recent call last):
  File "/home/pset/you/workspace/PycharmProjects/nds_tool/middleWare/test2.py", line 51, in <module>
    assert NumVertices.build(result) == b'\x02\x30'
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 218, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 230, in build_stream
    self._build(obj, stream, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 1721, in _build
    buildret = self.subcon._build(obj, self.stream2, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 1270, in _build
    subobj = self.subcon._build(obj, stream, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 867, in _build
    buildret = sc._build(subobj, stream, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 310, in _build
    return self.subcon._build(obj, stream, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 1509, in _build
    case._build(obj, stream, context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 597, in _build
    if obj < 0 and not self.signed:
TypeError: unorderable types: NoneType() < int()
```

**Comment by OhBonsai** [comment]
**Add two simple test**
```
testBit = BitStruct(
    'a' / BitsInteger(8),
    'b' / If(lambda ctx: ctx.a == 97, BitsInteger(8))
)
assert testBit.parse(b'ab') == Container(a=97, b=98)

testByte = Struct(
    'a' / Byte,
    'b' / If(lambda ctx: ctx.a == 97, Byte)
)
assert testByte.parse(b'ab') == Container(a=97, b=98)

print(testByte.build(Container(a=97, b=98)))
print(testBit.build(Container(a=97, b=98)))

```

**Comment by OhBonsai** [comment]
Another test
```
>>> NumVertices = Union(
...     'numVx4' / Bitwise(Aligned(Struct('hehe'/ BitsInteger(4)), modulus=8)),
...     'numVx8' / Bitwise(Aligned(Struct('hehe'/ BitsInteger(12)), modulus=8)),
...     'numVx16' / Bitwise(Aligned(Struct('hehe'/ BitsInteger(28)), modulus=8)),
... )
>>> con = NumVertices.parse(b'\x01\x34\x56\x78')
>>> blob = NumVertices.build(con)
>>> blob
b''

```

**Comment by arekbulski** [comment]
In first, Aligned does no longer take `modulus` keyword, look it up. Second code is fine. Third is well, it parses and builds but not reversibly and it didnt make much sense in the first place. You should re-write it.
```py
NumVertices = Bitwise(Aligned(8, Struct(
    'numVx4' / BitsInteger(4),
    'numVx8' / If(this.numVx4 == 0, BitsInteger(8)),
    'numVx16' / If(this.numVx4 == 0 and this.numVx8 == 255, BitsInteger(16)),
)))
common(NumVertices, b'\x02\x30', Container(numVx4=0, numVx8=35, numVx16=None))

testBit = BitStruct(
    'a' / BitsInteger(8),
    'b' / If(this.a == 97, BitsInteger(8))
)
testByte = Struct(
    'a' / Byte,
    'b' / If(this.a == 97, Byte)
)
common(testBit, b'ab', Container(a=97, b=98))
common(testByte, b'ab', Container(a=97, b=98))

NumVertices = Union(
    'numVx4' /  Bitwise(Aligned(8, Struct('num'/ BitsInteger(4)))),
    'numVx8' /  Bitwise(Aligned(8, Struct('num'/ BitsInteger(12)))),
    'numVx16' / Bitwise(Aligned(8, Struct('num'/ BitsInteger(28)))),
)
common(NumVertices, b'\x01\x34\x56\x70', Container(numVx4=Container(num=0))
(numVx8=Container(num=19))(numVx16=Container(num=1262951)))
```

**Comment by arekbulski** [comment]
Oh just so you know the terminology. Most constructs have a propery that they re-parse and re-build meaning parse and build are reverse to each other. Look at definition of `common()`.

**Comment by OhBonsai** [comment]
Hi, where is  ```common()``` ?
I can't find doc in ```http://construct.readthedocs.io/en/latest/genindex.html```

**Comment by arekbulski** [comment]
It's used internally in test_all.

**Comment by arekbulski** [comment]
Half of this test case is still broken, I reopen to look at it.
