### ISSUE TITLE
Struct inside Union fails to build

### ISSUE THREAD

**Issue by VanhaKehno** [construct/construct#270]
Struct inside Union containing other values such as Int8ub will not build. UnionError is raised claiming that other member needs to be initialised also, which is peculiar as union's idea is to be able to choose between union members. Union with noncomplex data members such as integers works fine.
```
>>> t = Union(
    Struct('c' / Int8ub, 'd' / Int8ub),
    'b' / Int8ub[2]
    )
>>> t.build(dict(c=2, d=3))
```
```
Traceback (most recent call last):
  File "<pyshell#150>", line 1, in <module>
    t.build(dict(c=2, d=3))
  File "C:\Python27\lib\site-packages\construct\core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "C:\Python27\lib\site-packages\construct\core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "C:\Python27\lib\site-packages\construct\core.py", line 1398, in _build
    raise UnionError("none of subcons %s were found in the dictionary %s" % (self.subcons, obj))
UnionError: none of subcons [<Peek: None +nonbuild>, <Peek: b +nonbuild>] were found in the dictionary {'c': 2, 'd': 3}
```

**Comment by arekbulski** [comment]
Because you got it wrong. Union needs all its members named (Struct isnt). Parsing union would yield
`Container('st'=Container(c=?,d=?), b=?)` so build needs `dict(st=dict(c=?,d=?))`.

**Comment by VanhaKehno** [comment]
Okay. Now i understand. Cheers for helping me out.

**Comment by arekbulski** [comment]
Your welcome :)
