### ISSUE TITLE
RawCopy problems

### ISSUE THREAD

**Issue by eaut** [construct/construct#289]
I am having problems with RawCopy()
```
tst = Struct(
	"raw" / RawCopy(Struct(
		"x" / Byte, 
		"len" / Byte,
	)),
	"array" / Array(this.raw.value.len, Byte),
)

# test 1 - OK
print(tst.parse(b"\x01\x02\xff\x00"))

# test 2 - OK
print(tst.build(dict(raw=dict(value=dict(x=1, len=2)), array=[0xff, 0x01])))

# test 3 - ERROR
print(tst.build(tst.parse(b"\x01\x02\xff\x00")))

# test 4 - ERROR
print(tst.build(dict(data=b"\x01\x02\xff\x00")))
```
Why do tests 3 and 4 fail? Is this a bug in RawCopy or am I missing something?

**Comment by arekbulski** [comment]
In case 4 the struct should get a "raw" item that is what RawCopy requires to build from, which is a dict having either a "data" or "value" item, or even both for that matter. The dict you provide does not have a "raw" item. 

In case 3, no idea. Should work.

**Comment by eaut** [comment]
Thank you for your fast reply. I have changed test 4 as you suggested. But it still fails. Below the actual error messages for 3 and 4.
```
>>> from construct import *
>>> tst = Struct(
...     "raw" / RawCopy(Struct(
...             "x" / Byte, 
...             "len" / Byte,
...     )),
...     "array" / Array(this.raw.value.len, Byte),
... )
>>> tst.build(tst.parse(b"\x01\x02\xff\x00"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 874, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 2704, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 996, in _build
    min = self.min(context) if callable(self.min) else self.min
  File "/usr/lib/python3.5/site-packages/construct/expr.py", line 145, in __call__
    context2 = self.__parent(context)
  File "/usr/lib/python3.5/site-packages/construct/expr.py", line 146, in __call__
    return context2[self.__name]
KeyError: 'value'
>>> tst.build(dict(raw=dict(data=b"\x01\x02\xff\x00")))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 873, in _build
    subobj = obj[sc.name]
KeyError: 'array'
```
I can fix Error 3 by switching the "if / elif" statements in RawCopy, but I am not sure if that is fully correct. My assumption is that a new object should always be built from the "value" part if both "data" and "value" are provided. 
```
ORIGINAL
---------------
    def _build(self, obj, stream, context, path):
        if 'data' in obj: 
            data = obj['data'] 
            _write_stream(stream, len(data), data) 
            return Container(data=data, length=len(data))
        elif 'value' in obj:
            value = obj['value']
            data = self.subcon.build(value, context)
            _write_stream(stream, len(data), data)
            return Container(data=data, value=value, length=len(data))
WORKING
---------------
    def _build(self, obj, stream, context, path):
        if 'value' in obj:
            value = obj['value']
            data = self.subcon.build(value, context)
            _write_stream(stream, len(data), data)
            return Container(data=data, value=value, length=len(data))
        elif 'data' in obj:
            data = obj['data']
            _write_stream(stream, len(data), data)
            return Container(data=data, value=value, length=len(data))
```
The fix for error 4 could be that if only "data" is available the "value" fields are generated from the "data" part through parsing during _build to allow later referencing. I do not know how to code that properly.

**Comment by eaut** [comment]
The test case 4 statement was still wrong, now it should be right. And surprise, the error is now identical with error 3 and my coding to fix case 4 "value missing" works too. 
```
>>> tst.build(dict(raw=dict(data=b"\x01\x02"),array=[0xff, 0x01]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 874, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 2704, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/usr/lib/python3.5/site-packages/construct/core.py", line 996, in _build
    min = self.min(context) if callable(self.min) else self.min
  File "/usr/lib/python3.5/site-packages/construct/expr.py", line 145, in __call__
    context2 = self.__parent(context)
  File "/usr/lib/python3.5/site-packages/construct/expr.py", line 146, in __call__
    return context2[self.__name]
KeyError: 'value'
```
Attached a revised version of _build that **WORKS** for cases 1-4.
```
    def _build(self, obj, stream, context, path):
        if 'value' in obj:
            value = obj['value']
            data = self.subcon.build(value, context)
            _write_stream(stream, len(data), data)
            return Container(data=data, value=value, length=len(data))
        elif 'data' in obj:
            data = obj['data']
            value = self.subcon.parse(data)
            _write_stream(stream, len(data), data)
            return Container(data=data, value=value, length=len(data))
        else:
            raise ConstructError('both data and value keys are missing')
```

**Comment by arekbulski** [comment]
I finally understand what causes this problem. When you build from a full dict that has all the keys, the `if data` kicks in, and replaces the context entry with a subset of a dict it had to begin with. I fixed it to merge new entries with the original dict.

Test 4 is NOT PASSABLE because (1) array length cannot be deduced from a raw copy (bytes).

**Comment by arekbulski** [comment]
Fixed.

**Comment by eaut** [comment]
Thanks for fixing case #3, but I think that the fixed case #4 (below) should not fail:
```
print(tst.build(dict(raw=dict(data=b"\x01\x02"),array=[0xff, 0x01])))
```
My assumption is that a `value = self.subcon.parse(data)` or something similar is missing when the `if data` branch is executed.  
Which argument should be used for building in case both "value" and "data" are provided and they are not identical? With the current `if ... elif` order it uses  "data" argument and discards changes made in "value".

**Comment by arekbulski** [comment]
Test case 4 is not passable, because `array` requires a context extry that is not passed explicitly and cannot be implied from raw bytes. 
```py
st = Struct(
	"raw" / RawCopy(Struct("x" / Byte, "len" / Byte)),
	"array" / Byte[this.raw.value.len],
)
print(st.build(dict(raw=dict(data=b"\x01\x02\xff\x00")))) 
```
If both raw bytes and object are provided then it is assumed and rightfully so that they are the same. Bytes representation is used because it is computationally cheaper.

**Comment by eaut** [comment]
Maybe my numbering is confusing you. Let's call the following case #5:
```
print(tst.build(dict(raw=dict(data=b"\x01\x02"),array=[0xff, 0x01])))
```
It should work?

**Comment by arekbulski** [comment]
No. The `array` subcon not only needs a list of ints which you provide, but it also needs a context entry corresponding to `this.raw.value.len`, and this one is not there. And it cannot be computed from the raw bytes either.
