### ISSUE TITLE
Problem with Array when parsing socket stream

### ISSUE THREAD

**Issue by tomgankema** [construct/construct#292]
I have problems using Array when parsing from a socket stream. The same FORMAT works fine when not using a socket stream.

See the following example:

**server.py**
```python
import socket
import construct

# this works
FORMAT_GOOD = construct.Bytes(6)
# this does not
FORMAT_BAD = construct.Array(2, construct.Bytes(3))

serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
serversocket.bind(('localhost', 8089))
serversocket.listen(5)

while True:
    clientsocket, address = serversocket.accept()
    sock = clientsocket.makefile('rb')
    while True:
        # this works:
        #message = FORMAT_GOOD.parse_stream(sock)
        # this does not:
        message = FORMAT_BAD.parse_stream(sock)
        print(message)
        next_message = sock.peek(1)
        if next_message == b'':
            break
    clientsocket.close()

serversocket.close()
```
**client.py**
```python
import socket

clientsocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
clientsocket.connect(('localhost', 8089))
clientsocket.sendall(b'\x30\x30\x30\x30\x30\x30')
```
Traceback
```
Traceback (most recent call last):
  File "/lib/python3.5/site-packages/construct/core.py", line 997, in _parse
    fallback = stream.tell()
io.UnsupportedOperation: seek

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 21, in <module>
    message = FORMAT_BAD.parse_stream(sock)
  File "/lib/python3.5/site-packages/construct/core.py", line 186, in parse_stream
    return self._parse(stream, context, "parsing")
  File "/lib/python3.5/site-packages/construct/core.py", line 1004, in _parse
    raise RangeError("expected %d to %d, found %d" % (min, max, len(obj)))
construct.core.RangeError: expected 2 to 2, found 0
```

**Comment by arekbulski** [comment]
I cant know for sure but it is possible that the socket reads do not block and therefore do not provide the amount of bytes requested by the classes. You could try the experimental:
https://construct.readthedocs.io/en/latest/streaming.html#construct.core.Rebuffered
