### ISSUE TITLE
If() raises exception when embedded

### ISSUE THREAD

**Issue by SzieberthAdam** [construct/construct#296]
Consider the following `constructissue.py`:

```Python
from construct import *
from construct.lib import *

BuggedStruct = 'BuggedStruct' / Struct(
  'ctrl' / OneOf(Bytes(1), b'\x02\x06\x15'),
  Probe(),
  Embedded(If(
    this.ctrl == b'\x02',
    Struct('etx' / Const(b'\x03')),
  )),
)

WorkaroundStruct = 'WorkaroundStruct' / Struct(
  'ctrl' / OneOf(Bytes(1), b'\x02\x06\x15'),
  Probe(),
  Embedded(IfThenElse(
    this.ctrl == b'\x02',
    Struct('etx' / Const(b'\x03')),
    Struct()
  )),
)

p1 = BuggedStruct.parse(b'\x02\x03')
p2 = WorkaroundStruct.parse(b'\x06')
p3 = BuggedStruct.parse(b'\x06')
```

This one raises an exception for `p3`:

```
================================================================================
Probe <unnamed 1>
path is parsing -> BuggedStruct, func is None
0000   03                                                                                                .

Container:
    ctrl = b'\x02'
================================================================================
================================================================================
Probe <unnamed 2>
path is parsing -> WorkaroundStruct, func is None
EOF reached
Container:
    ctrl = b'\x06'
================================================================================
================================================================================
Probe <unnamed 1>
path is parsing -> BuggedStruct, func is None
EOF reached
Container:
    ctrl = b'\x06'
================================================================================
Traceback (most recent call last):
  File "bug001.py", line 27, in <module>
    p3 = BuggedStruct.parse(b'\x06')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\construct\core.py", line 175, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\construct\core.py", line 186, in parse_stream
    return self._parse(stream, context, "parsing")
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\construct\core.py", line 2715, in _parse
    return self.subcon._parse(stream, context, path)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\construct\core.py", line 855, in _parse
    subobj = list(sc._parse(stream, context, path).items())
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by arekbulski** [comment]
I think you got it wrong. The `Embedded(If(...))` was not meant to work like that. `If` returns a None and `Embedded` works with Structs/dicts only. The so called workaround is the proper way to go about it. 

Also I rejected the PR because catching an AttributeError is not the way to resolve this. If anything the code should check if a None was given instead of a dict.

**Comment by arekbulski** [comment]
I welcome you to add a test case for the workaround to the suite. Look up how the suite is made.

**Comment by arekbulski** [comment]
Thank you for raising (uh pun unintended) this issue. I will fix it in spare time.

**Comment by arekbulski** [comment]
Issue fixed. Thanks for patiance.
