### ISSUE TITLE
Encoding errors (2.5.2)

### ISSUE THREAD

**Issue by ChillarAnand** [construct/construct#305]
I am trying to port isign to Python 3 which uses construct internally. isign fails on python3 with this error even though all the data sent to construct is just text.

```
Traceback (most recent call last):
  File "/home/chillaranand/.virtualenvs/py35/bin/isign", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/chillaranand/projects/appknox/isign/bin/isign", line 190, in <module>
    isign.resign(app_path, **kwargs)
  File "/home/chillaranand/projects/appknox/isign/isign/isign.py", line 76, in resign
    info_props)
  File "/home/chillaranand/projects/appknox/isign/isign/archive.py", line 394, in resign
    ua.bundle.resign(signer, provisioning_profile)
  File "/home/chillaranand/projects/appknox/isign/isign/bundle.py", line 244, in resign
    super(App, self).resign(signer)
  File "/home/chillaranand/projects/appknox/isign/isign/bundle.py", line 171, in resign
    self.sign(signer)
  File "/home/chillaranand/projects/appknox/isign/isign/bundle.py", line 167, in sign
    executable.sign(self, signer)
  File "/home/chillaranand/projects/appknox/isign/isign/signable.py", line 139, in sign
    offset, new_codesig_data = self._sign_arch(arch, app, signer)
  File "/home/chillaranand/projects/appknox/isign/isign/signable.py", line 87, in _sign_arch
    arch['codesig'].resign(app, signer)
  File "/home/chillaranand/projects/appknox/isign/isign/codesig.py", line 309, in resign
    self.set_codedirectory(bundle.seal_path, bundle.info_path, signer)
  File "/home/chillaranand/projects/appknox/isign/isign/codesig.py", line 230, in set_codedirectory
    cd.bytes = macho_cs.CodeDirectory.build(cd.data)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 212, in build
    self.build_stream(obj, stream)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 219, in build_stream
    self._build(obj, stream, Container())
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 691, in _build
    sc._build(subobj, stream, context)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 862, in _build
    case._build(obj, stream, context)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 981, in _build
    self.subcon._build(obj, stream, context)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 273, in _build
    self.subcon._build(obj, stream, context)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/core.py", line 290, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/construct/adapters.py", line 236, in _encode
    return StringAdapter._encode(self, obj, context) + self.terminators[0:1]
TypeError: Can't convert 'bytes' object to str implicitly
```

However after patching construct [with this fix](https://github.com/construct/construct/commit/7860c8b5ba8c5e074579577eccb91051074e8aa0#diff-7c026ac506e4f662c2dffc766940b27c), isign is working fine.

**Comment by arekbulski** [comment]
It looks to me like you are fixing the core which aint broken. Python3 uses unicode strings when Python2 used bytes. What you probably are doing is reading bytes and treating them as if they were strings, withouth decoding through some explicit encoding like UTF8.

**Comment by arekbulski** [comment]
Oh if you meant to really use bytes and not strings, then you should use Bytes/GreedyBytes and not String classes. In Construct 2.8 this distinction was made clear, previously these two were confused together somehow.

**Comment by ChillarAnand** [comment]
@arekbulski Thanks for clarifying that. 

isign still uses `construct==2.5.2`.

Here is the struct that is used

```
CodeDirectory = Struct("CodeDirectory",
                       Anchor("cd_start"),
                       UBInt32("version"),
                       UBInt32("flags"),
                       UBInt32("hashOffset"),
                       UBInt32("identOffset"),
                       UBInt32("nSpecialSlots"),
                       UBInt32("nCodeSlots"),
                       UBInt32("codeLimit"),
                       UBInt8("hashSize"),
                       UBInt8("hashType"),
                       UBInt8("spare1"),
                       UBInt8("pageSize"),
                       UBInt32("spare2"),
                       Pointer(lambda ctx: ctx['cd_start'] - 8 + ctx['identOffset'], CString('ident')),
                       If(lambda ctx: ctx['version'] >= 0x20100, UBInt32("scatterOffset")),
                       If(lambda ctx: ctx['version'] >= 0x20200, UBInt32("teamIDOffset")),
                       If(lambda ctx: ctx['version'] >= 0x20200, Pointer(lambda ctx: ctx['cd_start'] - 8 + ctx['teamIDOffset'], CString('teamID'))),
                       Pointer(lambda ctx: ctx['cd_start'] - 8 + ctx['hashOffset'] - ctx['hashSize'] * ctx['nSpecialSlots'], Hashes)
                       )
```

For this data 

```
    cd_start = 60
    version = 131584
    flags = 0
    hashOffset = 180
    identOffset = 52
    nSpecialSlots = 5
    nCodeSlots = 1478
    codeLimit = 6051392
    hashSize = 20
    hashType = 1
    spare1 = 0
    pageSize = 12
    spare2 = 0
    ident = 'com.appknox.dvia'
    scatterOffset = 0
    teamIDOffset = 69
    teamID = '76254KB9K7'
    hashes = [bytearray(b'\xff\xa5\x03dG\xcf\xa6Y+CS\xe5d\xc2\x1f\x94X\xf9m\xe7'), bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00')]
````

With Python 2 & Python 3, I am using same data & same types. However 
```
CodeDirectory.build(data)
```
succeeds in 2 & fails in 3.

**Comment by arekbulski** [comment]
To be honest, construct 2.5 is NO LONGER supported. I dont even care about bug fixes for it. The release is downloadable but I wont invest time into fixing something that was abandoned.
