### ISSUE TITLE
Container can be parsed, but result not build

### ISSUE THREAD

**Issue by rrooij** [construct/construct#373]
First of all, I'm sorry if this is a "common sense" question. I tried many things and read the documentation but still couldn't figure out the problem.

This is the interactive console:

```python
>>> save = open('/home/myuser/Downloads/SEIKEN3.srm', 'r+b')
>>> data = save_format.parse_stream(save)
>>> data
Container(One=Container(header=Container(char1=Container(name='Lise')(lvl=31)(current_hp=527)(max_hp=527)(current_mp=58)(max_mp=58))(playing_music=50)(char2=Container(name='Kevin')(lvl=31)(current_hp=617)(max_hp=617)(current_mp=49)(max_mp=49))(location_name=21)(char3=Container(name='Angela')(lvl=31)(current_hp=420)(max_hp=420)(current_mp=76)(max_mp=76))(time_played=44999.73333333333))(data=Container(length=1934)(offset2=2046)(offset1=112)(value=Container(still_unknown=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 1, 14, 18, 1, 0, 18, 16, 2, 64, 27, 89, 24, 0, 2, 21, 0, 1, 21, 0, 16, 47, 23, 22, 2, 51, 3, 5, 3, 8, 16, 20, 10, 16, 35, 21, 3, 17, 17, 1, 0, 0, 0, 2, 1, 0, 0, 0, 5, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 1, 1, 1, 1, 1, 1, 15, 1, 1, 2, 2, 21, 15, 15, 15, 15, 15, 15, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 16, 0, 117, 112, 0, 0, 64, 0, 0, 0, 0, 0, 0, 16, 1, 5, 255, 54, 0, 0, 248, 24, 5, 1, 3, 0, 2, 240, 18, 0, 2, 1, 3, 14, 9, 1, 0, 0, 133, 0])(char1=Container(current_hp=527)(current_mp=58)(strength=17)(agility=12)(vitality=16)(int=10)(spirit=11)(luck=9)(total_exp=2)(remainder_total_exp=-18820)(tech_gauge_max=7)(exp_for_next_level=3)(remainder_exp_next_level=11086)(lvl=31)(character_skin=5)(class_change_made=1)(class=0)(equipped_weapon=-37)(equipped_helmet=65)(equipped_armor=-19)(equipped_gauntlet=122)(equipped_shield=0)(attack_power=167)(evade_rate=25)(defense_power=211)(magic_defense_power=85)(unkown_could_be_power=93)(extra_weapons=[-45, -44, -43, -40, -39, 0, 0])(extra_armor=[61, 62, 63, 0, 0, 0, 0])(extra_gauntlets=[118, 120, 0, 0, 0, 0, 0])(extra_shields=[0, 0, 0, 0, 0, 0, 0])(spells=[4, 10, 16, 22, 0, 0, 0, 0, 0, 0, 0, 0])(targeting_values=[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])(max_hp=527)(max_mp=58))(char2=Container(current_hp=617)(current_mp=49)(strength=15)(agility=12)(vitality=16)(int=8)(spirit=10)(luck=8)(total_exp=2)(remainder_total_exp=-17374)(tech_gauge_max=7)(exp_for_next_level=3)(remainder_exp_next_level=11086)(lvl=31)(character_skin=1)(class_change_made=1)(class=0)(equipped_weapon=60)(equipped_helmet=17)(equipped_armor=-99)(equipped_gauntlet=86)(equipped_shield=0)(attack_power=197)(evade_rate=25)(defense_power=190)(magic_defense_power=69)(unkown_could_be_power=85)(extra_weapons=[44, 45, 48, 49, 51, 54, 0])(extra_armor=[13, 14, 15, 0, 0, 0, 0])(extra_gauntlets=[82, 84, 0, 0, 0, 0, 0])(extra_shields=[0, 0, 0, 0, 0, 0, 0])(spells=[79, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])(targeting_values=[4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])(max_hp=617)(max_mp=49))(char3=Container(current_hp=420)(current_mp=76)(strength=9)(agility=8)(vitality=13)(int=18)(spirit=13)(luck=10)(total_exp=2)(remainder_total_exp=-18650)(tech_gauge_max=7)(exp_for_next_level=3)(remainder_exp_next_level=11086)(lvl=31)(character_skin=3)(class_change_made=1)(class=1)(equipped_weapon=-111)(equipped_helmet=41)(equipped_armor=-59)(equipped_gauntlet=105)(equipped_shield=0)(attack_power=132)(evade_rate=21)(defense_power=198)(magic_defense_power=149)(unkown_could_be_power=109)(extra_weapons=[-128, -127, -124, -123, -120, 0, 0])(extra_armor=[37, 38, 39, 0, 0, 0, 0])(extra_gauntlets=[100, 102, 0, 0, 0, 0, 0])(extra_shields=[0, 0, 0, 0, 0, 0, 0])(spells=[31, 1, 7, 25, 13, 26, 19, 0, 0, 0, 0, 0])(targeting_values=[3, 3, 3, 3, 3, 1, 3, 0, 0, 0, 0, 0])(max_hp=420)(max_mp=76))(character_names=['Lise', 'Kevin', 'Angela'])(luc=31579)(item_storage=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 7, 0, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 23, 0, 31, 4, 0, 0, 1, 0, 0, 4, 0, 71, 1, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 42, 8, 10, 0, 47, 15, 3, 3, 1, 0, 0, 1, 0, 8, 0, 0, 0, 0, 0])(location=3847)(item_ring=[0, 89, 84, 85, 92, 83, 95, 88, 36, 86]))(data=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+\x01\x0e\x12\x01\x00\x12\x10\x02@\x1bY\x18\x00\x02\x15\x00\x01\x15\x00\x10/\x17\x16\x023\x03\x05\x03\x08\x10\x14\n\x10#\x15\x03\x11\x11\x01\x00\x00\x00\x02\x01\x00\x00\x00\x05\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x02\x02\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x02\x02\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x02\x00\x01\x01\x01\x01\x01\x01\x0f\x01\x01\x02\x02\x15\x0f\x0f\x0f\x0f\x0f\x0f\x01\x01\x03\x03\x03\x03\x03\x03\x03\x03\x01\x01\x00\x00\x00\x00\x00\x01\x01\x00\x10\x00up\x00\x00@\x00\x00\x00\x00\x00\x00\x10\x01\x05\xff6\x00\x00\xf8\x18\x05\x01\x03\x00\x02\xf0\x12\x00\x02\x01\x03\x0e\t\x01\x00\x00\x85\x00\x0f\x02:\x00\x11\x0c\x10\n\x0b\t\x02\x00|\xb6~\x0f\x02:\x00\x07\x03\x00N+\x1f\x14\x05\x01\x00\xdbA\xedz\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z<\x1e\x00\x00\x00\t\xa7\x00\x00\x00\x00\x00\x00\x19\xd3\x00U\x00]\x00\xd3\xd4\xd5\xd8\xd9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00=>?\x00\x00\x00\x00\x00\xe3\xe4\xe5\xe6\xe8\xe9\xea\x00vx\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\n\x10\x16\x00\x00\x00\x00\x00\x00\x00\x00\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x0f\x02:\x00\x00\xff\x05\x00\x00\t\x00\x00\x00$\x02\x00\x03\x00\x07\x03\t\x01\x00\x00\x00\x00\x03\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x81\x00i\x021\x00\x0f\x0c\x10\x08\n\x08\x02\x00"\xbc~i\x021\x00\x07\x03\x00N+\x1f\x0e\x01\x01\x00<\x11\x9dV\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00xZ<\x00\x00\x00\x08\xc5\x00\x00\x00\x00\x00\x00\x19\xbe\x00E\x00U\x00,-0136\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\x0e\x0f\x00\x00\x00\x00\x00\x94\x95\x96\x98\x99\x9a\x00\x00RT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00O!\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00i\x021\x00\x02\xff\x01\x00\x03\x0c\x00\x00\x00\x07\x01\x01\x02\x00\x00\x01\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x83\x00\xa4\x01L\x00\t\x08\r\x12\r\n\x02\x00&\xb7~\xa4\x01L\x00\x07\x03\x00N+\x1f\x10\x03\x01\x01\x91)\xc5i\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x1e\x01\x00\x00\x00\n\x84\x00\x00\x00\x00\x00\x00\x15\xc6\x00\x95\x00m\x00\x80\x81\x84\x85\x88\x00\x00\x00h\x00\x00\x00\x00\x00\x00\x00%&\'\x00\x00\x00\x00\x00\xbc\xbd\xbe\xc0\xc1\xc2\x00\x00df\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x01\x07\x19\r\x1a\x13\x00\x00\x00\x00\x00\x03\x03\x03\x03\x03\x01\x03\x00\x00\x00\x00\x00\xa4\x01L\x00\x00\xff\x03\x00\x00\x07\x00\x00\x00\x17\x01\x01\x02\x00\x00\x05\x01\x00\x00\x00\x00\x00\x03\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00L\x00i\x00s\x00e\x00\x00\x00\x00\x00K\x00e\x00v\x00i\x00n\x00\x00\x00A\x00n\x00g\x00e\x00l\x00a\x00[{\x00\x00\x03\x02\x00\x02\x00\x02\x00\x02\x00\x02\x00\x02\x00\x02\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x04\x08\x10 @\x80\x01\x02\x04\x08\x10 @\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x01\x00\x00\x01\x07\x00\x02\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\x18\x00\x00\x17\x00\x1f\x04\x00\x00\x01\x00\x00\x04\x00G\x01\x03\x00\x03\x00\x00\x00\x00\x00\x00\x00\x01\x01\x00\x01\x01\x00\x00\x01*\x08\n\x00/\x0f\x03\x03\x01\x00\x00\x01\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x07\x0f\x01\x00\x00~\x00h\x00\x01\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00L\x89\x0f\x01\x03\x1c\x18\x01Q\xa9\r\x01\xea@\x07\x00\xc7\xdd\xa6\x00\xd02)\x00\x03\x00YTU\\S_X$V?\x08\t\t\x01\t\x01\x06\t\x04\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'))(checksum=24924))(Two=None)(Three=None)
>>> save_format.build(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 193, in build
    self.build_stream(obj, stream, context, **kw)
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 205, in build_stream
    self._build(obj, stream, context, "building")
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 872, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 2717, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 872, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 2717, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py", line 871, in _build
    subobj = obj[sc.name]
KeyError: None
>>> import pdb
>>> pdb.pm()
> /home/myuser/git/seiken3save_editorpy/venv/lib/python3.5/site-packages/construct/core.py(871)_build()
-> subobj = obj[sc.name]
(Pdb) subobj
(Pdb) obj
Container(char1=Container(name='Lise')(lvl=31)(current_hp=527)(max_hp=527)(current_mp=58)(max_mp=58))(playing_music=50)(char2=Container(name='Kevin')(lvl=31)(current_hp=617)(max_hp=617)(current_mp=49)(max_mp=49))(location_name=21)(char3=Container(name='Angela')(lvl=31)(current_hp=420)(max_hp=420)(current_mp=76)(max_mp=76))(time_played=44999.73333333333)
(Pdb) subobj
(Pdb) dir()
['buildret', 'context', 'i', 'obj', 'path', 'sc', 'self', 'stream', 'subobj']
(Pdb) i
1
(Pdb) obj
Container(char1=Container(name='Lise')(lvl=31)(current_hp=527)(max_hp=527)(current_mp=58)(max_mp=58))(playing_music=50)(char2=Container(name='Kevin')(lvl=31)(current_hp=617)(max_hp=617)(current_mp=49)(max_mp=49))(location_name=21)(char3=Container(name='Angela')(lvl=31)(current_hp=420)(max_hp=420)(current_mp=76)(max_mp=76))(time_played=44999.73333333333)
(Pdb) path
'building -> One -> header'
(Pdb) sc
<Range: None>
(Pdb) sc
<Range: None>
(Pdb) sc.name
(Pdb) 
```

As we can see, the data is parsed correctly, but the same data cannot be build again.
There is an example save in the attachments for testing purposes.
[SEIKEN3.tar.gz](https://github.com/construct/construct/files/1069261/SEIKEN3.tar.gz)
Of course, the archive should be extracted first.

My binary structure:

```python
from sd3save_editor import checksum
from construct import (Adapter, Byte, Checksum, Const, Struct,
                       Int8sl, Int16sb, Int16sl, Int16ul, Int32sl,
                       String,  this, RawCopy, Optional)

class TimeAdapter(Adapter):
    """Convert seconds to seiken densetsu 3 time
       Time is saved as a 60th of a second
    """
    def _decode(self, obj, context):
        return obj / 60

    def _encode(self, obj, context):
        return obj * 60


class CharacterNameAdapter(Adapter):
    """Convert name to utf16-le"""

    def _decode(self, obj, context):
        replace_char = '\x00'
        return obj.decode('utf-16-le',
                          'backslashreplace').rstrip(replace_char)

    def _encode(self, obj, context):
        zeroes = bytearray(7 - len(obj))
        return (obj + zeroes).encode('utf-16-le')


char_header = Struct(
    "name"/CharacterNameAdapter(String(12, padchar=b'')),
    "lvl"/Int8sl,
    "current_hp"/Int16sl,
    "max_hp"/Int16sl,
    "current_mp"/Int16sl,
    "max_mp"/Int16sl,
    Byte[7]
)

save_header = Struct(
    Const(b"exist   "),
    Byte[8],
    "char1"/char_header,
    "playing_music"/Int8sl,
    Byte[3],
    "char2"/char_header,
    "location_name"/Int8sl,
    Byte[3],
    "char3"/char_header,
    "time_played"/TimeAdapter(Int32sl)
)

character_stats = Struct(
    "current_hp"/Int16sl,
    "current_mp"/Int16sl,
    "strength"/Int8sl,
    "agility"/Int8sl,
    "vitality"/Int8sl,
    "int"/Int8sl,
    "spirit"/Int8sl,
    "luck"/Int8sl,
    "total_exp"/Int16sl,
    "remainder_total_exp"/Int16sl,
    Byte[5],
    "tech_gauge_max"/Int8sl,
    "exp_for_next_level"/Int16sl,
    "remainder_exp_next_level"/Int16sl,
    "lvl"/Int8sl,
    Byte,
    "character_skin"/Int8sl,
    "class_change_made"/Int8sl,
    "class"/Int8sl,
    "equipped_weapon"/Int8sl,
    "equipped_helmet"/Int8sl,
    "equipped_armor"/Int8sl,
    "equipped_gauntlet"/Int8sl,
    "equipped_shield"/Int8sl,
    Byte[19],  # Not known yet :(
    "attack_power"/Int16sl,
    Byte[5],  # Also unkown
    "evade_rate"/Int8sl,
    "defense_power"/Int16sl,
    "magic_defense_power"/Int16sl,
    "unkown_could_be_power"/Int16sl,
    "extra_weapons"/Int8sl[7],
    Byte[9],
    "extra_armor"/Int8sl[7],  # TODO: Do something with extra equipment
    Byte[9],  # Unknown,
    "extra_gauntlets"/Int8sl[7],
    Byte,  # Unknown
    "extra_shields"/Int8sl[7],
    Byte,  # Unkown
    "spells"/Int8sl[12],
    "targeting_values"/Int8sl[12],
    "max_hp"/Int16sl,
    "max_mp"/Int16sl
)

save_data = Struct(
    "still_unknown"/Byte[258],
    "char1"/character_stats,
    Byte[112],
    "char2"/character_stats,
    Byte[112],
    "char3"/character_stats,
    Byte[110],
    "character_names"/CharacterNameAdapter(String(12, padchar=b''))[3],
    "luc"/Int16ul,
    Byte[529],
    "item_storage"/Int8sl[103],
    Byte[26],
    "location"/Int16sl,
    Byte[46],
    "item_ring"/Int8sl[10],
    Byte[159]
)

save_entry = Struct(
    "header"/save_header,
    "data"/RawCopy(save_data),
    "checksum"/Checksum(Int16sb,
                        lambda data: checksum.sum16_checksum(data),
                        this.data.data)
)


save_format = Struct(
    "One"/save_entry,
    "Two"/Optional(save_entry),
    "Three"/Optional(save_entry)
)

```

It reads all the data correctly and I have no idea why it can't be build again. The Container is a dictionary type and should be read correctly by the build function.

**Comment by potens1** [comment]
Hi @rrooij ,
I'm not sure this is your problem but at first glance, you have a lot of "unamed" fields ( Byte instead of "foo" / bytes), so, when you parse stream, the parser is able to fill those "unamed" fields, since it knows how to parse it, but, then, those are lost in the resulting container, since they were never assigned to anything.

When you want to build, from a previously parsed stream, or from new container, you dan't have a way to put data in the fields, but those are mandatory, so the builder can not work.

I think this is your problem (but I had a very fast glance).

Hope this helps.

PS: to be clear:
```python
save_header = Struct(
    Const(b"exist   "),
    Byte[8],
    "char1"/char_header,
    "playing_music"/Int8sl,
    Byte[3],
    "char2"/char_header,
    "location_name"/Int8sl,
    Byte[3],
    "char3"/char_header,
    "time_played"/TimeAdapter(Int32sl)
)
```
You are not able to put the required 8 bytes before "char1", "char2" and "char3"

**Comment by rrooij** [comment]
@potens1 You are right! That was the problem!

I'm wondering: would it be a nice addition to have a generated name of unnamed fields? I now have to call them names like "unknown1", "unknown2" etc.

**Comment by potens1** [comment]
@rrooij 

It already exists in more than one form, have a look to http://construct.readthedocs.io/en/latest/misc.html#padding, http://construct.readthedocs.io/en/latest/misc.html#const, maybe http://construct.readthedocs.io/en/latest/misc.html#default

```Python
foo = Struct(
     Const(b"\x01"),
     Padding(4),
     "data" / Byte[2],
     Padding(2),
     Const(b"\xff"))
```
```
In [369]: foo.build({"data":[16,17]})
Out[369]: b'\x01\x00\x00\x00\x00\x10\x11\x00\x00\xff'

In [370]: foo.parse(foo.build({"data":[16,17]}))
Out[370]: Container(data=[16, 17])
```

**Comment by arekbulski** [comment]
Yes, @potens1 is right. `Padding` is goint to work. Also I would consider `Bytes(5)` instead of `Byte[5]`.

**Comment by rrooij** [comment]
Thanks for the answers and advice. I'm using the bigger byte size instead of the arrays now.

A somewhat related question: I'm using RawCopy to calculate the checksum, but I only want to edit the `value` of RawCopy and not the raw data. I'm now manually removing the binary data from the dictionary, like this (see function write_save):

https://github.com/rrooij/sd3save_editor/blob/master/sd3save_editor/save.py#L152

**Comment by arekbulski** [comment]
RawCopy code rules, during building, if both data and value are present then only data is used due to better performance (value would have to be serialized into a data).
https://github.com/construct/construct/blob/master/construct/core.py#L2133

**Comment by rrooij** [comment]
I understand the performance considerations, but wouldn't it be a nice option to be able to ignore it? I now have to manually delete the data type if I build the binary again.

**Comment by arekbulski** [comment]
Rule of thumb is, if you can manually edit the value then you can also manually... edit (remove) data? I wont add that kind of feature, no one would use it.

**Comment by rrooij** [comment]
You're right and I understand the decision. Thanks for helping out so far. It is indeed a very small task to delete the data.

My problems so far are solved. Thank you! I will consider contributing to the project in ways I can.

**Comment by arekbulski** [comment]
Another reason is that the codebase (few classes at least) is beyond my comprehesion already (are unmaintainable). Adding more and more features for the sake of few people is not worth doing.
