### ISSUE TITLE
CStrings and utf-16 codec

### ISSUE THREAD

**Issue by agodnic** [construct/construct#388]
Hello!
I noticed construct.CString does not properly work with python's utf-16 and utf-16-le codecs.

An example encoding:
```
>>> import construct
>>> construct.CString(encoding='utf-16-le').build('abcd')
b'a\x00'
```
This is not the utf-16-le encoding of abcd, as shown here:
```
>>> 'abcd'.encode('utf-16-le')
b'a\x00b\x00c\x00d\x00'
```

A decoding example:

```
>>> 'abcd'.encode('utf-16-le') + b'\x00\x00'
b'a\x00b\x00c\x00d\x00\x00\x00'
>>> construct.CString(encoding='utf-16-le').parse('abcd'.encode('utf-16-le') + b'\x00\x00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 165, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 176, in parse_stream
    return self._parse(stream, context, "parsing")
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 304, in _parse
    return self._decode(self.subcon._parse(stream, context, path), context)
  File "/usr/local/lib/python3.4/dist-packages/construct/core.py", line 3245, in _decode
    obj = obj.decode(encoding)
  File "/usr/lib/python3.4/encodings/utf_16_le.py", line 16, in decode
    return codecs.utf_16_le_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x61 in position 0: truncated data
```

**Comment by arekbulski** [comment]
That is a known bug. CString simply cannot work with the kind of terminator that >1 encodings use. I thought there was a warning in the docs about this but apparently there isnt. I added warnings in docs.

Also thank you for the snippets, I added them to test suite.

**Comment by agodnic** [comment]
Thanks @arekbulski!

Then I'll use ```construct.PascalString``` instead, which works with utf-16.

By the way, having a PascalString field in a struct does not seem to work, am I doing something wrong?

```
>>> construct.Struct('field1'/construct.PascalString(construct.Byte)).build('abcd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 193, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 205, in build_stream
    self._build(obj, stream, context, "building")
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 863, in _build
    context.update(obj)
  File "/usr/local/lib/python2.7/dist-packages/construct/lib/container.py", line 150, in update
    for k, v in seqordict:
ValueError: need more than 1 value to unpack
```

I know I could also define it using ```>>``` but I don't like the fact that fields are unnamed after decoding.

**Comment by arekbulski** [comment]
Yes, PascalString works with those encodings. Error is probably you did not specify encoding there, so it expecs bytes during building while you provile (implicitly) unicode. The exception is not helpful, I know.

You got it exactly right. `>>` make a sequence, `/` make a struct, one has named subcons and other has anonymous subcons.

**Comment by agodnic** [comment]
Hmm doesn't work either when providing an encoding:

```
>>> construct.Struct('field1'/construct.PascalString(construct.Byte, encoding='utf-8')).build('abcd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 193, in build
    self.build_stream(obj, stream, context, **kw)
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 205, in build_stream
    self._build(obj, stream, context, "building")
  File "/usr/local/lib/python2.7/dist-packages/construct/core.py", line 863, in _build
    context.update(obj)
  File "/usr/local/lib/python2.7/dist-packages/construct/lib/container.py", line 150, in update
    for k, v in seqordict:
ValueError: need more than 1 value to unpack
>>>
```

**Comment by arekbulski** [comment]
That looks kind of like a bug. I will look at it.

**Comment by arekbulski** [comment]
`PascalString(construct.Byte, encoding='utf-8')).build('abcd')`
You provide a bytes but any encoding means you need to provide unicode string to build.

**Comment by arekbulski** [comment]
UTF16 UTF32 support was added to all String classes, available in next release.
