### ISSUE TITLE
Nested arrays of indexed length

### ISSUE THREAD

**Issue by marnunez** [construct/construct#401]
There's a section on a file that begins with a list, say:
`a = [15,28,57,49]`
and what follows is a list `b` of the same length as `a`, whose contents are Arrays of Floats of length `a[i]` (the first array has 15 items, the second 28, etc)

Meaning: I have to create an Array of Arrays: the parent one of `len(a)`, and the nested one of `len(a[i])`
`````python
everything = Struct(
'a' / Array(4,Int),
'b' / Array(len_(this.a),Array(...
`````
And that's where I struggle. How can I do this without indexing? I can make the first Array (`a[0] = 15`), or any other for that matter, which is not the desired behaviour (this makes all nested Arrays of length 15)

`````python
everything = Struct(
'a' / Array(4,Int),
'b' / Array(len_(this.a),Array(this.a[0],Float))
`````
Can I somehow make `len(a)` Arrays of length `len(a[i])` and then unite them with Union, perhaps?

**Comment by arekbulski** [comment]
Maybe a custom adapter?

**Comment by arekbulski** [comment]
Just write a custom adapter, that will encapsulate entire Struct. Make decoding that adds additional fields to the parsed dict... if you dont have a class that does something, write your  own...

**Comment by marnunez** [comment]
Well, I ended up writing a modified version of Range that goes "deeper" into obj. Is this what you ment by writing my own class? Too much overkill?

````python
class ListDefinedArray(Subconstruct):
    # lenarray = Array with the computed lengths for each list
    def __init__(self,lenarray,subcon):
        super(ListDefinedArray,self).__init__(subcon)
        self.lenarray = lenarray

    def _parse(self, stream, context, path):
        context = Container(context)
        lenarray = self.lenarray(context) if callable(self.lenarray) else self.lenarray
        obj = ListContainer()
        for i in lenarray:
            inner_obj = ListContainer()
            try:
                while len(inner_obj) < i:
                    fallback = stream.tell()
                    inner_obj.append(self.subcon._parse(stream, context._, path))
                    context[len(inner_obj)-1] = inner_obj[-1]
                obj.append(inner_obj)
            except StopIteration:
                pass
            except ExplicitError:
                raise
            except Exception:
                if len(obj) < i:
                    raise RangeError("expected %d to %d, found %d" % len(obj))
                stream.seek(fallback)
        return obj

    def _build(self,obj,stream,context,path):
        context = Container(context)
        lenarray = self.lenarray(context) if callable(self.lenarray) else self.lenarray
        try:
            for subobj in obj:
                for j,inner_sub_obj in enumerate(subobj):
                    context[j] = inner_sub_obj
                    self.subcon._build(inner_sub_obj, stream, context._, path)
        except StopIteration:
            pass
        except ExplicitError:
            raise
        except Exception:
            if len(obj) < len(lenarray):
                raise RangeError("expected %d to %d, found %d" % len(obj))
            else:
                raise

    def _sizeof(self, context, path):
        try:
            lenarray = self.lenarray(context) if callable(self.lenarray) else self.lenarray
        except (KeyError, AttributeError):
            raise SizeofError("cannot calculate size, key not found in context")
        if lenarray:
            return lenarray * self.subcon._sizeof(context, path)
        else:
            raise SizeofError("cannot calculate size")
````

**Comment by arekbulski** [comment]
I think writing an Adapter would be easier than extending Range, and much more readable but if that works for you, why not. You can close the thread.

**Comment by marnunez** [comment]
Ok then, noted for refactoring. I'll see if I can get my head around using Adapters for this kind of stuff.

**Comment by marnunez** [comment]
Ok, sorry for reviving this post. There's something I can't figure out with the Adapter approach to this nested arrays of indexed length thing.

```python
from construct import *


exampleData = {
    "leng": 4,                                      # Size of the lengths array
    "lengths_array": [2, 1, 1, 1],                  # Sizes of every array within var_lengths_array
    "var_lengths_array": [[1, 2], [1], [3], [4]]    # Actual data
    }

stream = Struct(
    "leng" / Int32sl,
    "lengths_array" / Array(this.leng, Int32sl)
    # Cant add var_lengths_array here, not created yet
    )


class ListArray(Adapter):
    # def _decode(self, obj, context, path):
    #     print(obj)
    #     return obj

    def _encode(self, obj, context, path):
        a = "var_lengths_array" / Struct()
        for i in obj["lengths_array"]:
            a.subcons.append(Array(i, Int32sn))
        self.subcon.subcons.append(a)
        return obj

a = ListArray(stream)
print(a.build(exampleData))
```
this fails with:

> Traceback (most recent call last):
>   File "c:/Users/marcha/Desktop/Marcos/tdfparser/tdfparser/BTSString.py", line 30, in <module>
>     print(a.build(Container(exampleData)))
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 353, in build
>     self.build_stream(obj, stream, **contextkw)
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 366, in build_stream
>     self._build(obj, stream, context, "(building)")
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 722, in _build
>     buildret = self.subcon._build(obj2, stream, context, path)
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 2006, in _build
>     buildret = sc._build(subobj, stream, context, path)
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 2475, in _build
>     return self.subcon._build(obj, stream, context, path)
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\core.py", line 1995, in _build
>     context.update(obj)
>   File "c:\Users\marcha\Desktop\Marcos\tdfparser\.venv\lib\site-packages\construct\lib\containers.py", line 183, in update
>     for k,v in seqordict:
> ValueError: not enough values to unpack (expected 2, got 1)
> 
> 

I can't understand what am I missing here. Any advice?

**Comment by arekbulski** [comment]
WTF is the adapter manipulating subcons in _encode? That method is used to build a value that would be passed to subcons...

**Comment by marnunez** [comment]
Where do you say I should be manipulating the subcons? I think there's no "subcon to pass a value to", since the Struct I'm adapting doesn't have the proper "var_lengths_array" yet. I have to build it somewhere. I figured that before building the value, I'd create the actual array and only then pass the value.

**Comment by marnunez** [comment]
Allright, back to the start then. Forget my example.

I have a binary file that contains data in this form:

**len_a** (an integer)
**A** (an array of lengths): this array contains a list of integers.
**B** (an array of arrays): this array contains an array of arrays, each of them of length **A[i]**. There's **len_A** arrays in here. While encoding, **B** should read from the stream exacly **A[i]** integers for each array **i**

As I understand it, adapters are used to adapt the encoding and decoding of data from and into a Subconstruct (like in the datetime example, or IP address example). In this case, if A where, for example, [1,3,1,4], I'd have to modify B to contain Arrays of length 1, 3, 1, and 4 respectibly, so that they can read 1 integer, 3 integers, 1 integer and lastly 4 integers form the stream into each array of B.

So, if I make a Struct:

```python
datablock = Struct(
    "len_A" / Int32sl,                 # read first the length of A. No trouble here
    "A" / Array(this.len_A, Int32sl),   # read len_A integers. Fine
    # How do I add B here?? I've got to read the amount of Arrays to declare from A first!
    )
```
That's why I was manipulating the sucons. I figured I have to create B with the right amount of Arrays before encoding. Does this makes a bit more sense now?

**Comment by arekbulski** [comment]
Its almost trivial.
```
Struct(
  'rowcount' / Int,
  'colcounts' / Array(this.rowcount, Int),
  'jaggedarray' / Array(this.rowcount, Array(lambda this: this.colcounts[this._index], Int))
)
```
If you can change the format then it would be easier to have each row prefixed instead:
```
Struct(
  'jaggedarray' / PrefixedArray(Int, PrefixedArray(Int, Int))
)
```
