### ISSUE TITLE
BitsInteger swapped=True with non-multiple of 8 bits

### ISSUE THREAD

**Issue by wsadkj** [construct/construct#415]
```
class BitsInteger(Construct):
    def _parse(self, stream, context, path):
        length = self.length(context) if callable(self.length) else self.length
        data = _read_stream(stream, length)
        if self.swapped:
            data = swapbytes(data, 8)  **# data might not be multiple of 8, should this be "data = data[::-1]"?**
return bits2integer(data, self.signed)
```

**Comment by arekbulski** [comment]
You need to provide an example of failure, preferrably as assert line.

**Comment by wsadkj** [comment]
Sample:`Sample = BitStruct(
    'field1' / BitsInteger(3, swapped=True),
    'field2' / BitsInteger(5, swapped=True),
)
if __name__ == '__main__':
    print (Sample.parse(b'\x35'))`

failure assert:
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 1835, in _parse
    obj = self.subcon._parse(stream2, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 591, in _parse
    data = swapbytes(data, 8)
  File "C:\Program Files\Python36\lib\site-packages\construct\lib\binary.py", line 138, in swapbytes
    raise ValueError("data length must be multiple of linesize")
ValueError: data length must be multiple of linesize
>

**Comment by arekbulski** [comment]
BitsInteger swaps octets (eight bits) within the field. It cannot be swapped and not multiple of 8. Thats 3 and 5 BIT not bytes.

**Comment by wsadkj** [comment]
I wish to have these fields interpreted as little endian.  If swap cannot work, any better way to achieve this without hacking core.py?

**Comment by arekbulski** [comment]
Little endian by definition refers to swapping octets within a field, as I described. If you want to swap the 3 bits in the field, which is NOT same as little-endian, you can use a wrapper class `BitsSwapped`. Little endian means using `BytesSwapped`.
https://construct.readthedocs.io/en/latest/tunneling.html#endianness

**Comment by wsadkj** [comment]
OK. Little endian machine might interpret C bit fields structure differently. See [http://mjfrazer.org/mjfrazer/bitfields/ ]  I wish to mimic the C data structure for little endian machine. 

Directly wrap BitInteger with BitsSwap does not see work?
`def SwappedBitInteger(length):
    return BitsSwapped(BitsInteger(length, signed=False))

Sample = BitStruct(
    'field1' / SwappedBitInteger(3),
    'field2' / SwappedBitInteger(5),
    )

if __name__ == '__main__':
    print(Sample.parse(b'\x11'))`

It will triggers the assert:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 1835, in _parse
    obj = self.subcon._parse(stream2, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 1835, in _parse
    obj = self.subcon._parse(stream2, context, path)
  File "C:\Program Files\Python36\lib\site-packages\construct\core.py", line 592, in _parse
    return bits2integer(data, self.signed)
  File "C:\Program Files\Python36\lib\site-packages\construct\lib\binary.py", line 71, in bits2integer
    number = (number << 1) | onebit2integer(b)
  File "C:\Program Files\Python36\lib\site-packages\construct\lib\binary.py", line 55, in onebit2integer
    raise ValueError(r"bit was not recognized as one of: 0 1 \x00 \x01")
ValueError: bit was not recognized as one of: 0 1 \x00 \x01

Any suggestion? Thanks a lot!

**Comment by arekbulski** [comment]
Useful link. Non-octet endianness is just INSANITY. I wont add any support for it. You need to write your own class for it, modify BitsInteger or BitsSwapped to your needs.

**Comment by arekbulski** [comment]
There is a problem with this line. BitsSwapped works in BYTEWISE context, not BITWISE. Thats why the error.
```py
return BitsSwapped(BitsInteger(length, signed=False))
```

**Comment by wsadkj** [comment]
Yes, this looks like a neat solution for me! Thank you so much for the quick support:)
