### ISSUE TITLE
Can not access parent context from inner structure in OnDemand 

### ISSUE THREAD

**Issue by red-hood** [construct/construct#53]
Hi, it seems the context for inner structures is not constructed if they are used in an OnDemand construct, e.g.:

```python
from construct import Struct, String, UBInt8, OnDemand

inner = Struct('inner',
               String('innerstring', lambda ctx: ctx._.length, encoding='utf-8'),
               )

outer = Struct('outer',
               UBInt8('length'),
               OnDemand(inner),
               )
```
Trying to parse  the length-prefixed sting leads to an exception:

    >>> outer.parse(b'\x03abc')
    AttributeError: length

(for full trace see below).

If the OnDemand is removed in the example above, everything works fine. Is this a bug, or did I miss something?

Full trace:
```
ERROR:root:length
Traceback (most recent call last):
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/lib/container.py", line 33, in __getattr__
    return self[name]
KeyError: 'length'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-153-9b84b0441fcc>", line 2, in <module>
    outer.parse(b'\x03abc')
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 1052, in _parse
    stream.seek(self.subcon._sizeof(context), 1)
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 695, in _sizeof
    return sum(sc._sizeof(context) for sc in self.subcons)
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 695, in <genexpr>
    return sum(sc._sizeof(context) for sc in self.subcons)
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 275, in _sizeof
    return self.subcon._sizeof(context)
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/core.py", line 402, in _sizeof
    return self.lengthfunc(context)
  File "<ipython-input-87-ce9b61e96ee4>", line 2, in <lambda>
    String('innerstring', lambda ctx: ctx._.length, encoding='utf-8'),
  File "/home/ich/.virtualenvs/construct/lib/python3.4/site-packages/construct/lib/container.py", line 35, in __getattr__
    raise AttributeError(name)
AttributeError: length
```

**Comment by arekbulski** [comment]
This looks like a PascalString so you could use just that. As for the ctx._.length, I have absolutely no clue where in the code is the _ key added. It might as well not exist. Some docs are stale. Docstrings are almost always uptodate.

**Comment by arekbulski** [comment]
One of the future changes to be made is adding LazyStruct and LazyRange. That will deprecate the OnDemand class and make this issue kind of go away.
