### ISSUE TITLE
sizeof() for construct depending on its parent

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#692]
Found at https://stackoverflow.com/questions/44747202/pythons-construct-sizeof-for-construct-depending-on-its-parent

**Comment by DominicAntonacci** [comment]
This is a 2.9 regression. The following small example runs in Construct 2.8.22 but fails in Construct 2.9.45
```python
from construct import Struct, Int8ub, Bytes, this
d = Struct(
        'length' / Int8ub,
        'data' / Bytes(this.length))

a = d.parse(b'\x04beef')
print(d.sizeof(**a))
```

**A Workaround for 2.9.45**
Based off the code, the size can be computed from each of subcons. For the the minimal example, you can get the size with
`sum(sc.sizeof(**a) for sc in d.subcons)`

**Full Traceback**
I've included the full traceback as well. The context doesn't appear to be getting passed correctly to `_sizeof`, but I didn't debug it further than that.
```
Traceback (most recent call last):
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 866, in _sizeof
    return self.length(context) if callable(self.length) else self.length
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\expr.py", line 188, in __call__
    return self.__parent(obj)[self.__field]
KeyError: 'length'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "construct_test.py", line 14, in <module>
    print(d.sizeof(**a))
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 398, in sizeof
    return self._sizeof(context, "(sizeof)")
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 2014, in _sizeof
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 2014, in <genexpr>
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 2476, in _sizeof
    return self.subcon._sizeof(context, path)
  File "C:\anaconda3\envs\construct_debugging\lib\site-packages\construct\core.py", line 868, in _sizeof
    raise SizeofError("cannot calculate size, key not found in context")
construct.core.SizeofError: cannot calculate size, key not found in context
```
