### ISSUE TITLE
BitStruct cannot be embedded

### ISSUE THREAD

**Issue by Sanqui** [construct/construct#708]
```python
from construct import *

d = Struct(
    'byte' / Byte,
    Embedded(BitStruct(
       'bit' / Bit,
       'padding' / Padding(7)
    ))
)
```

```
Traceback (most recent call last):
  File "/home/sanqui/test.py", line 7, in <module>
    'padding' / Padding(7)
  File "/home/sanqui/.local/share/virtualenvs/datamijn-pCt6ETHm/lib/python3.6/site-packages/construct/core.py", line 1963, in __init__
    self.subcons = mergefields(*subcons)
  File "/home/sanqui/.local/share/virtualenvs/datamijn-pCt6ETHm/lib/python3.6/site-packages/construct/core.py", line 197, in mergefields
    result.extend(select(sc))
  File "/home/sanqui/.local/share/virtualenvs/datamijn-pCt6ETHm/lib/python3.6/site-packages/construct/core.py", line 189, in select
    return select(sc.subcon)
  File "/home/sanqui/.local/share/virtualenvs/datamijn-pCt6ETHm/lib/python3.6/site-packages/construct/core.py", line 192, in select
    raise ConstructError("Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct")
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct
```

In previous version of Construct, it was possible to embed a BitStruct.  It would be useful.

**Comment by arekbulski** [comment]
Dont take it the wrong way but I do know it would be useful, I dont need to be told that. If you had searched other issues then you would already know that this feauture was already asked for, discussed, and requested multiple times. And I also already explained: embedding semantics just had to be changed, and under these its impossible to embed Bitwise, which makes up a BitStruct.

**Comment by Sanqui** [comment]
I'm sorry, I'm not sure what I was thinking when I made the issue.  Thank you.
