### ISSUE TITLE
Prefixed(Embedded(Struct))) works with construct 2.8.12 but does not with 2.9.45

### ISSUE THREAD

**Issue by pckbls** [construct/construct#750]
Hi there,

I just attempted to make the transition from construct 2.8.12 to 2.9.45 and I stumpled across a possible(?) bug when combining `construct.Embedded(construct.Struct))` with a `construct.Prefixed` statement.

The following Python script works perfectly fine with construct 2.8.12:
```python
#!/usr/bin/env python3


import sys
import construct


INNER_PARSER = construct.Struct(
    'lol' / construct.Int8ul,
    'rofl' / construct.Int8ul
)

OUTER_PARSER = construct.Struct(
    'foo' / construct.Int32ul,
    construct.Prefixed(
        construct.Int16ul,
        construct.Embedded(INNER_PARSER)
    )
)


def read():
    with open('data.bin', 'rb') as f:
        binary = f.read()

    parsed = OUTER_PARSER.parse(binary)
    print(parsed)


def write():
    binary = OUTER_PARSER.build({
        'foo': 1337,
        'lol': 42,
        'rofl': 128
    })
    with open('data.bin', 'wb') as f:
        f.write(binary)


if __name__ == '__main__':
    if sys.argv[1] == 'read':
        read()
    elif sys.argv[1] == 'write':
        write()
    else:
        print('Usage: {0} <read|write>'.format(sys.argv[0]))
        sys.exit(-1)

    sys.exit(0)
```

It produces the following output:
```
➜  ConstructBug ./broken.py write
➜  ConstructBug hexdump data.bin 
0000000 0539 0000 0002 802a                    
0000008
➜  ConstructBug ./broken.py read 
Container: 
    foo = 1337
    lol = 42
    rofl = 128
```

When executing the script with construct 2.9.45 it'll throw a weird Exception:
```
➜  ConstructBug ./broken.py write
Traceback (most recent call last):
  File "./broken.py", line 17, in <module>
    construct.Embedded(INNER_PARSER)
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 1963, in __init__
    self.subcons = mergefields(*subcons)
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 197, in mergefields
    result.extend(select(sc))
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 192, in select
    raise ConstructError("Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct")
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct

➜  ConstructBug ./broken.py read
Traceback (most recent call last):
  File "./broken.py", line 17, in <module>
    construct.Embedded(INNER_PARSER)
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 1963, in __init__
    self.subcons = mergefields(*subcons)
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 197, in mergefields
    result.extend(select(sc))
  File "/home/patrick/.local/lib/python3.7/site-packages/construct/core.py", line 192, in select
    raise ConstructError("Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct")
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct
```

Is this a bug or intentional behavior? Any chance to fix this?

Thanks in advance,
Patrick

**Comment by arekbulski** [comment]
> construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct

Ah that isnt a bug, its a restriction on embedding semantics. Read the docs. You cannot embed struct (or rather their fields) into any class, embedding only works when outter class is like a Struct or similar.

**Comment by pckbls** [comment]
Thanks for your reply, I understand.

It would have helped if the exception message was more clear. I initially assumed that the message refers to the **inner** statement, therefore `Embedded(Struct)` works whereas `Embedded(Byte)` should not. That got me confused.

**Comment by arekbulski** [comment]
In 2.10 embedding was dropped entirely. Yay finally gone.
