### ISSUE TITLE
Aligned does not preserve the correct context of a nested subcon when calculating the size of the Padding

### ISSUE THREAD

**Issue by nucular** [construct/construct#76]
When wrapping a nested construct such as a `Struct` within an `Aligned`, the context passed to the `padlength` function that calculates the size of the `Padding` (and subsequently `subcon._sizeof` and all constructs contained within it) is the parent context, not the context of the construct. This results in most meta constructs failing since they are being passed the wrong context.

The following example, which tries to parse a word-aligned struct that consists of a variable-length field `bar`, prefixed by its length `foo`, makes the issue evident:

```py
def barLength(ctx):
  print("Context of bar is", ctx)
  return ctx.foo

Test = Struct("test1",
  Aligned(
    Struct("test2",
      ULInt8("foo"),
      Field("bar", barLength)
    ),
    modulus=4
  )
)

print(Test.parse(b"\x02\xAB\xCD\x00"))
```
Output:
```
Context of bar is Container:
    foo = 2

Context of bar is Container:
    test2 = Container:
        foo = 2
        bar = b'\xab\xcd'

Traceback (most recent call last):
  File "C:\tools\python\lib\site-packages\construct\lib\container.py", line 33, in __getattr__
    return self[name]
KeyError: 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    Test.parse(b"\x02\xAB\xCD\x00")
  File "C:\tools\python\lib\site-packages\construct\core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "C:\tools\python\lib\site-packages\construct\core.py", line 198, in parse_stream

    return self._parse(stream, Container())
  File "C:\tools\python\lib\site-packages\construct\core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 733, in _parse
    subobj = sc._parse(stream, context)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 398, in _parse
    return _read_stream(stream, self.lengthfunc(context))
  File "C:\tools\python\lib\site-packages\construct\macros.py", line 379, in padlength
    return (modulus - (subcon._sizeof(ctx) % modulus)) % modulus
  File "C:\tools\python\lib\site-packages\construct\core.py", line 695, in _sizeof
    return sum(sc._sizeof(context) for sc in self.subcons)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 695, in <genexpr>
    return sum(sc._sizeof(context) for sc in self.subcons)
  File "C:\tools\python\lib\site-packages\construct\core.py", line 402, in _sizeof
    return self.lengthfunc(context)
  File "test.py", line 14, in barLength
    return ctx.foo
  File "C:\tools\python\lib\site-packages\construct\lib\container.py", line 35, in __getattr__
    raise AttributeError(name)
AttributeError: foo
```

As you can see, on the second call to `barLength` it is being passed the context of `test1` instead of the context of `test2`.

**Comment by arekbulski** [comment]
You nested `Aligned` within a `Struct`, not the other way around. And does that nesting also produce an error?

Could you add a test case for both nestings based on this code abd submit a pull request?

**Comment by arekbulski** [comment]
The printed context actually does contain `foo` attribute. I do not understand it.

```python
In [36]: Test = Struct("test1",
  Aligned(
    Struct("test2",
      ULInt8("foo"),
      Field("bar", lambda ctx: print(ctx))
    ), modulus=4
  )
)

In [37]: print(Test.parse(b"\x02\xAB\xCD\x00"))
Container:
    foo = 2
# then error occurs
```

**Comment by arekbulski** [comment]
Aligned could be made to measure how many bytes were written to the steam using tell method instead of using sizeof. Sizeof itself needs a huge redesign.

**Comment by arekbulski** [comment]
You should know that Aligned was recently reimplemented so it uses stream tell instead of subcon sizeof. Therefore this code works OK.
```py
In [3]: Aligned(CString('name'), modulus=8).parse(b'1234\0pad')
Out[3]: b'1234'
```

**Comment by arekbulski** [comment]
This code works OK now. I will add this to the test suite.

```py
def barLength(ctx):
  print("Context of bar is", ctx)
  return ctx.foo

Test = Struct("test1",
  Aligned(
    Struct("test2",
      ULInt8("foo"),
      Field("bar", barLength)
    ),
    modulus=4
  )
)

print(Test.parse(b"\x02\xAB\xCD\x00"))
```
