### ISSUE TITLE
Porting ironic-inspector to construct 2.9

### ISSUE THREAD

**Issue by josch** [construct/construct#772]
Hi,

I'm trying to prepare a new version of construct for Debian but noticed that the openstack service [ironic-inspector](https://github.com/openstack/ironic-inspector) fails to build with construct 2.9:

```
Failed to import test module: ironic_inspector.test.unit.test_plugins_lldp_basic
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3/dist-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/ironic_inspector/test/unit/test_plugins_lldp_basic.py", line 16, in <module>
    from ironic_inspector.common import lldp_parsers as nv
  File "/<<PKGBUILDDIR>>/ironic_inspector/common/lldp_parsers.py", line 22, in <module>
    from ironic_inspector.common import lldp_tlvs as tlv
  File "/<<PKGBUILDDIR>>/ironic_inspector/common/lldp_tlvs.py", line 137, in <module>
    mapping_for_switch(CHASSIS_ID_MAPPING)))
  File "/usr/lib/python3/dist-packages/construct/core.py", line 1963, in __init__
    self.subcons = mergefields(*subcons)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 197, in mergefields
    result.extend(select(sc))
  File "/usr/lib/python3/dist-packages/construct/core.py", line 189, in select
    return select(sc.subcon)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 189, in select
    return select(sc.subcon)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 192, in select
    raise ConstructError("Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct")
construct.core.ConstructError: Embedding only works with: Struct Sequence FocusedSeq Union LazyStruct
```

I looked for documentation somewhere that explains how to port existing code from construct 2.8 to 2.9 but couldn't find any. Could you advise me how ironic-inspector would need to be changed to be compatible with construct 2.9?

Thanks!

**Comment by josch** [comment]
So, I never used construct before but even after having read the documentation, all I can come up with is to replace `core.Switch` with `core.EmbeddedSwitch` so that it can be embedded. The patch looks like this:

```
--- a/ironic_inspector/common/lldp_tlvs.py
+++ b/ironic_inspector/common/lldp_tlvs.py
@@ -133,7 +133,8 @@ ChassisId = core.Struct(
     'subtype' / core.Enum(core.Byte, **mapping_for_enum(
         CHASSIS_ID_MAPPING)),
     'value' /
-    core.Embedded(core.Switch(construct.this.subtype,
+    core.Embedded(core.EmbeddedSwitch(construct.this.subtype,
+                              construct.this.type,
                               mapping_for_switch(CHASSIS_ID_MAPPING)))
 )
 
```

**Comment by arekbulski** [comment]
I am too tired to read your entire posting, please forgive. Short answer is that people (userbase) just overused embedding as a feature waaaaay too much. Embedding should have not beed added in the first place and if it were not, it would be much better now. Whoever wrote the offending code is in it by his own foolishness. I wrote the damn documentation and nowwhere do  I say that embedding is recommended or fine or okay. I discourage it every occasion. I welcome a reply.

**Comment by arekbulski** [comment]
In 2.10 embedding was removed entirely.
