### ISSUE TITLE
KeyError in ctx upgrading from 2.9.38 to 2.9.45

### ISSUE THREAD

**Issue by latot** [construct/construct#799]
Hi, i have this project (forked), and i port it to 2.9 some time ago, the latest very very close working version was 2.9.38, i continue upgrading the functions but now fails something that works before.

```
import construct
construct.core.possiblestringencodings['shift_jis'] = 1

from nepugia import *
from nepugia.formats.gbnl_models import *

path = "/home/p/Documents/git/latot/python-nepugia/data"

def ReadData(ifile, imodel):
    item_file = open(os.path.join(path, 'database', ifile), "rb")
    item_db = GBNLFormat(imodel).parse_stream(item_file)
    item_file.close()
    return item_db

item = ReadData('stitem.gbin', ItemModel)
```
(the same code as always), now i'm getting this:

```
Traceback (most recent call last):
  File "/home/p/.local/lib64/python3.6/site-packages/construct/lib/containers.py", line 100, in __getattr__
    return self[name]
KeyError: 'footer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "work_script.py", line 15, in <module>
    item = ReadData('stitem.gbin', ItemModel)
  File "work_script.py", line 11, in ReadData
    item_db = GBNLFormat(imodel).parse_stream(item_file)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/home/p/.local/lib64/python3.6/site-packages/construct/core.py", line 2216, in _parse
    count = count(context)
  File "/home/p/Documents/git/latot/python-nepugia/nepugia/formats/gbnl.py", line 89, in <lambda>
    Array(lambda ctx: ctx.footer.row_count,
  File "/home/p/.local/lib64/python3.6/site-packages/construct/lib/containers.py", line 102, in __getattr__
    raise AttributeError(name)
AttributeError: footer
```

The problem is from here:
https://github.com/latot/python-nepugia/blob/4d4cd136097eb176cc61de40593ec2d619641d2b/nepugia/formats/gbnl.py#L88

I don't know why this error, if "footer" exist and is declared (works before), i can't found in the docs some change in ctx or similar to know why now fails.

Thx.

**Comment by latot** [comment]
Hi, i can confirm this problem is from 2.9.38 to 2.9.39.

**Comment by latot** [comment]
This commit cause this:

https://github.com/construct/construct/commit/83ccc4befb70bb31b439e5deb42c81582d6742a4

Note, if we name not the struct, the point for example, we will don't get any errores, but will not read the info.

**Comment by arekbulski** [comment]
The commit you mention: it requires explicit naming of blocks, subcons no longer use sub-name.
