### ISSUE TITLE
"Default(Byte, 0)" passes 'None' to adapter, should be '0'.

### ISSUE THREAD

**Issue by mungewell** [construct/construct#802]
This works OK with a null-adapter
```
$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from construct import *
>>> class Midi1u(Adapter):
...     def _decode(self, obj, context, path):
...          print(obj)
...          return(obj)
...     def _encode(self, obj, context, path):
...          print(obj)
...          return(obj)
... 
>>> 
>>> a = Struct("a"/ Midi1u(Default(Byte, 0)))
>>> 
>>> a.build({})
None
b'\x00'
```

But fails when you actually try something....
```
$ python3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from construct import *
>>> class Midi1u(Adapter):
...     def _decode(self, obj, context, path):
...          print(obj)
...          return(obj & 0x7f)
...     def _encode(self, obj, context, path):
...          print(obj)
...          return(obj & 0x7f)
... 
>>> 
>>> a = Struct("a"/ Midi1u(Default(Byte, 0)))
>>> 
>>> a.build({})
None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg/construct/core.py", line 354, in build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg/construct/core.py", line 366, in build_stream
  File "/usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg/construct/core.py", line 2022, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg/construct/core.py", line 2495, in _build
  File "/usr/local/lib/python3.6/dist-packages/construct-2.9.45-py3.6.egg/construct/core.py", line 720, in _build
  File "<stdin>", line 7, in _encode
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
>>>
```

**Comment by mungewell** [comment]
whoops, wrong order
```
>>> a = Struct("a"/ Default(Midi1u(Byte), 123))
>>> a.build({})
123
b'{'
```
