### ISSUE TITLE
padding and aligning bytes to modulus?

### ISSUE THREAD

**Issue by kratsg** [construct/construct#808]
How do I define something that can take in n-bytes and pad/align to multiple of 4-byte words? E.G. I would like to build an array of 32-bit words. So I expected (naively) for the following two examples to be identical:

```
>>> GreedyRange(Int32ub).parse('0000dead'.decode('hex'))
ListContainer([57005])
>>> GreedyRange(Int32ub).parse('dead'.decode('hex'))
ListContainer([])
```

However, `Int32ub` cannot parse correctly:

```
>>> Int32ub.parse('dead'.decode('hex'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 260, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 268, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 280, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 893, in _parse
    data = _read_stream(stream, self.length)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 84, in _read_stream
    raise StreamError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: could not read enough bytes, expected 4, found 2
```

If I can figure out a subcon that can parse 1,2,3 bytes and pad to 4-bytes -- then I'm good to go (as GreedyRange will handle the rest!)

**Comment by arekbulski** [comment]
Read about `Padding` and `Aligned` classes.
Also your example is wrong: `>>> Int32ub.parse(b'dead')`

**Comment by kratsg** [comment]
> Also your example is wrong: `>>> Int32ub.parse(b'dead')`

I am decoding to `hex` quickly using 'decode'. That is, I'm just using the struct equivalent like-so:

```
>>> import struct
>>> struct.pack(">H", 0xdead)
'\xde\xad'
>>> 'dead'.decode('hex')
'\xde\xad'
>>> len(b'dead')
4
>>> len('dead'.decode('hex'))
2
```

I've been trying to understand `Padded` and `Aligned` from the [docs](https://construct.readthedocs.io/en/latest/misc.html#alignment-and-padding) (but I don't fully appreciate the difference here). I've been struggling with getting them working as expected:

```
>>> Aligned(4, Byte).parse('dead'.decode('hex'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 260, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 268, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 280, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 3781, in _parse
    _read_stream(stream, pad)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 84, in _read_stream
    raise StreamError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: could not read enough bytes, expected 3, found 1
>>> Padded(4, Byte).parse('dead'.decode('hex'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 260, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 268, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 280, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 3715, in _parse
    _read_stream(stream, pad)
  File "/Users/kratsg/.virtualenvs/ironman/lib/python2.7/site-packages/construct/core.py", line 84, in _read_stream
    raise StreamError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
construct.core.StreamError: could not read enough bytes, expected 3, found 1
```

It seems like these are meant to help _build_ aligned/padded bytes, rather than parse unaligned/unpadded bytes.
