### ISSUE TITLE
KeyError on Struct build

### ISSUE THREAD

**Issue by danielhrisca** [construct/construct#847]
Hello, I've tried to understand why I get this error but it is not obvious to me.

this is my code:

```python
import construct
from pyxcp.types import (
    ConnectResponse,
    CommModeBasic,
    ResourceType,
)
print(construct.version)
print(
   CommModeBasic.build({
       "optional": 0,
       "slaveBlockMode": 0,
       "addressGranularity": 0,
       "byteOrder": 0,
   })
)

ConnectResponse.build(
    {
     "commModeBasic": {
           "optional": 0,
           "slaveBlockMode": 0,
           "addressGranularity": 0,
           "byteOrder": 0,
       },
       'maxCto':255,
       'maxDto': 4000,
       'protocolLayerVersion': 1,
       'transportLayerVersion': 1,
       'resource': {
           'dbg': 0,
           'pgm': 0,
           'stim': 0,
           'daq': 1,
           'calpag': 0,
       },
       
     }
)
```

Links to the structures definitions:
* [ConnectResponse](https://github.com/christoph2/pyxcp/blob/master/pyxcp/types.py#L340)
* [CommModeBasic](https://github.com/christoph2/pyxcp/blob/master/pyxcp/types.py#L324)
* [ResourceType](https://github.com/christoph2/pyxcp/blob/master/pyxcp/types.py#L294)

I get the following output:

```
(2, 10, 56)
b'\x00'

Traceback (most recent call last):

  File "<ipython-input-9-df4790ffa79e>", line 1, in <module>
    runfile('D:/TMP/temp.py', wdir='D:/TMP')

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/TMP/temp.py", line 40, in <module>
    'calpag': 0,

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\core.py", line 336, in build
    self.build_stream(obj, stream, **contextkw)

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\core.py", line 2005, in _build
    buildret = sc._build(subobj, stream, context, path)

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\core.py", line 2443, in _build
    return self.subcon._build(obj, stream, context, path)

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\core.py", line 3562, in _build
    condfunc = condfunc(context)

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\expr.py", line 160, in __call__
    lhs = self.lhs(obj) if callable(self.lhs) else self.lhs

  File "d:\user\02__pythonworkspace\_venv\lib\site-packages\construct\expr.py", line 193, in __call__
    return self.__parent(obj)[self.__field]

KeyError: 'byteOrder'
```

**Comment by danielhrisca** [comment]
I've seen that I need to provide the _byteOrder_ keyword argument to the build method
