### ISSUE TITLE
Switch Lambda Fails When Compiling

### ISSUE THREAD

**Issue by dantonacci** [construct/construct#866]
Construct returns an error when trying to compile a Struct that has a switch which uses a lambda function as a key. Minimal example below. A workaround is to wrap the Switch block in a RawCopy.

```python
from construct import *

# Example data.
data1 = bytes.fromhex('010203')
data2 = bytes.fromhex('020103')

# This Struct will cause an error when compiled.
m = Struct(
    'size' / Byte,
    'data' / Switch(lambda ctx: ctx.size, {1: Byte, 2: Int16ul}, default=Struct())
).compile()

# This Struct compiles as expected and is a workaround for the issue.
m2 = Struct(
    'size' / Byte,
    'data' / RawCopy(Switch(lambda ctx: ctx.size, {1: Byte, 2: Int16ul}, default=Struct()))
).compile()
```

Error
```
Traceback (most recent call last):
  File "scratch_construct_compile.py", line 16, in <module>
    'data' / Switch(lambda ctx: ctx.size, {1: Byte, 2: Int16ul}, default=Struct())
  File "C:\anaconda3\lib\site-packages\construct\core.py", line 443, in compile
    c = compile(source, '', 'exec')
  File "", line 43
    result['data'] = this['data'] = factory_3.get(<function <lambda> at 0x000001A0A0EE5B88>, compiled_5)(io, this)
                                                  ^
SyntaxError: invalid syntax
```

Output from dumping compile to a file
```
# generated by Construct, this source is for inspection only! do not import!
from construct import *
from construct.lib import *
from io import BytesIO
import struct
import collections
import itertools
def read_bytes(io, count):
    if not count >= 0: raise StreamError
    data = io.read(count)
    if not len(data) == count: raise StreamError
    return data
def restream(data, func):
    return func(BytesIO(data))
def reuse(obj, func):
    return func(obj)
linkedinstances = {}
linkedparsers = {}
len_ = len
sum_ = sum
min_ = min
max_ = max
abs_ = abs
formatfield_2 = struct.Struct('>B')
formatfield_4 = struct.Struct('<H')
factory_3 = {1 : lambda io,this: formatfield_2.unpack(read_bytes(io, 1))[0], 2 : lambda io,this: formatfield_4.unpack(read_bytes(io, 2))[0]}
def parse_struct_6(io, this):
    result = Container()
    this = Container(_ = this, _params = this['_params'], _root = None, _parsing = True, _building = False, _sizing = False, _subcons = None, _io = io, _index = this.get('_index', None))
    this['_root'] = this['_'].get('_root', this)
    try:
        pass
    except StopFieldError:
        pass
    return result
compiled_5 = lambda io,this: parse_struct_6(io, this)
def parse_struct_1(io, this):
    result = Container()
    this = Container(_ = this, _params = this['_params'], _root = None, _parsing = True, _building = False, _sizing = False, _subcons = None, _io = io, _index = this.get('_index', None))
    this['_root'] = this['_'].get('_root', this)
    try:
        result['size'] = this['size'] = formatfield_2.unpack(read_bytes(io, 1))[0]
        result['data'] = this['data'] = factory_3.get(<function <lambda> at 0x000001B93E5FEE58>, compiled_5)(io, this)
        pass
    except StopFieldError:
        pass
    return result
def parseall(io, this):
    return parse_struct_1(io, this)
compiled = Compiled(None, None, parseall)
```

Construct Version: 2.10.56
Python Version 3.7.7

**Comment by arekbulski** [comment]
Lambdas are not supported by the compiler. It used to say so in the restrictions, dunno why its not mentioned now.
https://construct.readthedocs.io/en/latest/compilation.html#restrictions
You can use a this expression instead.

**Comment by arekbulski** [comment]
Using RawCopy is pointless. RawCopy is not compilable, you effectively forgone compilation.

**Comment by dantonacci** [comment]
Thanks for the details about inner workings! I'll close this now as lambdas aren't supported.
