### ISSUE TITLE
construct 2.5.4 no longer supports unicode string names

### ISSUE THREAD

**Issue by joachimmetz** [construct/construct#87]
construct 2.5.4 no longer supports unicode string names
```
TypeError: ('name must be a string or None', u'year')
```

It appears removing six has caused this issue:
https://github.com/construct/construct/blame/master/construct/core.py#L99
https://github.com/construct/construct/commit/53b2fb2d9025e763733173caf82c3ca8c5f86ede

But per: https://pythonhosted.org/six/
```
six.string_types
Possible types for text data. This is basestring() in Python 2 and str in Python 3.
```

Sending a PR to fix this.

**Comment by joachimmetz** [comment]
https://github.com/construct/construct/pull/88

**Comment by joachimmetz** [comment]
For reference:
```
======================================================================
ERROR: engine.path_helper (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: engine.path_helper
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/log2timeline/plaso/tests/engine/path_helper.py", line 10, in <module>
    from plaso.containers import artifacts
  File "./plaso/containers/__init__.py", line 8, in <module>
    from plaso.containers import reports
  File "./plaso/containers/reports.py", line 6, in <module>
    from plaso.lib import timelib
  File "./plaso/lib/timelib.py", line 41, in <module>
    class Timestamp(object):
  File "./plaso/lib/timelib.py", line 109, in Timestamp
    construct.ULInt16(u'year'),
  File "/usr/lib/python2.7/dist-packages/construct/macros.py", line 138, in ULInt16
    return FormatField(name, "<", "H")
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 353, in __init__
    super(FormatField, self).__init__(name, self.packer.size)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 325, in __init__
    super(StaticField, self).__init__(name)
  File "/usr/lib/python2.7/dist-packages/construct/core.py", line 104, in __init__
    raise TypeError("name must be a string or None", name)
TypeError: ('name must be a string or None', u'year')
```

**Comment by arekbulski** [comment]
You discovered a second bug. When it tests if name starts with _ or < it uses agnostic string literal which fails on PY with unicode name. 

Fixed both and added regression tests.

**Comment by arekbulski** [comment]
Look at #86 .

**Comment by joachimmetz** [comment]
thx
