### ISSUE TITLE
Enum but with bytestrings (python3)

### ISSUE THREAD

**Issue by kratsg** [construct/construct#880]
I know, I know, this is probably out of scope of the project, but I'm hoping for some quick advice.

```python
>>> from construct import Enum, Bytes
>>> struct = Enum(Bytes(2), aa=b"aa", bb=b"bb", yy=b"yy")
>>>struct.parse(b"aa")
EnumIntegerString.new(b'aa', 'aa')
>>> struct.parse(b"bb")
EnumIntegerString.new(b'bb', 'bb')
>>> struct.parse(b"yy")
EnumIntegerString.new(b'yy', 'yy')
>>> struct.parse(b"xx")
Traceback (most recent call last):
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 1732, in _decode
    return self.decmapping[obj]
KeyError: b'xx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 698, in _parse
    return self._decode(obj, context, path)
  File "/Users/kratsg/.virtualenvs/itksn/lib/python3.7/site-packages/construct/core.py", line 1734, in _decode
    return EnumInteger(obj)
ValueError: invalid literal for int() with base 10: b'xx'
```

To me, it's pretty clear what the error is. The default behavior for `Enum` in `2.10` is to return as an integer (if possible). I wonder how we can override that behavior to return the (very nice) variation instead:

```python
>>> from construct import EnumIntegerString
>>> EnumIntegerString.new(b"xx", "xx")
EnumIntegerString.new(b'xx', 'xx')
```

or to use the subconstructor of the `Enum`

```python
>>> Bytes(2).parse(b"xx")
b'xx'
```

**Comment by arekbulski** [comment]
I think the problem is that its supposed to return an EnumIntegerString so it constructs a string, not bytes.Thats all I understand from your little experiment. Good luck.

**Comment by kratsg** [comment]
@arekbulski right. If you look here:

https://github.com/construct/construct/blob/master/construct/core.py#L1731-L1735 -- the default is to return `EnumInteger(obj)` instead of the provided subconstruct that the `Enum` was initialized with to do the trick. I can create an `EnumBytes` class to override this behavior for now?

```python
    def _decode(self, obj, context, path):
        try:
            return self.decmapping[obj]
        except KeyError:
            return EnumInteger(obj)
```

Here's what I ended up with if anyone runs into a similar thing

```python
from construct import Enum, EnumIntegerString

class EnumStr(Enum):
    def _decode(self, obj, context, path):
        try:
            return self.decmapping[obj]
        except KeyError:
            return EnumIntegerString.new(obj, '')
```

**Comment by arekbulski** [comment]
I think this whole EnumIntegerString is too convoluted and was a mistake in the long run.
