### ISSUE TITLE
RawCopy does not update 'data'

### ISSUE THREAD

**Issue by mfrager** [construct/construct#955]
I think this is a regression because this seems to have worked before. Tried to delete the 'data' key and then rebuild but get this error:

Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 88, in stream_read
    data = stream.read(length)
io.UnsupportedOperation: read

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mkkeepass.py", line 53, in <module>
    mgr.create_database()
  File "./mkkeepass.py", line 50, in create_database
    self.save()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 154, in save
    output = KDBX.build_file(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 355, in build_file
    self.build_stream(obj, f, **contextkw)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 348, in build_stream
    self._build(obj, stream, context, "(building)")
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 2006, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 2444, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 4288, in _build
    data = stream_read(stream, offset2-offset1, path)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/construct/core.py", line 90, in stream_read
    raise StreamError("stream.read() failed, requested %s bytes" % (length,), path=path)
construct.core.StreamError: Error in path (building) -> header
stream.read() failed, requested 253 bytes

I can't figure out why it is trying to read from a stream (which in this case is a BufferedWriter) when it should be generating new data.

**Comment by mfrager** [comment]
Fixed in latest version...
