### ISSUE TITLE
sizeof does not work on variable sized Struct

### ISSUE THREAD

**Issue by theberrigan** [construct/construct#957]
Hi,

I am trying to get sizeof Struct containing an If-field, but it fails.
I found this sample in the issue [#409](https://github.com/construct/construct/issues/409#issuecomment-340454970):

```py
In [5]: st = Struct("optional" / If(this.found, Byte))

In [6]: st.sizeof(found=1)
Out[6]: 1

In [7]: st.sizeof(found=0)
Out[7]: 0
```

As you can see it works. But when I try to do the same, the error appears:

```py
from construct import *

st = Struct("optional" / If(this.found, Byte))
st.sizeof(found=1)
```

Output:

```py
Traceback (most recent call last):
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2156, in _sizeof
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2156, in <genexpr>
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2662, in _sizeof
    return self.subcon._sizeof(context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 3861, in _sizeof
    condfunc = evaluate(self.condfunc, context)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 198, in evaluate
    return param(context) if callable(param) else param
  File "C:\Python\39x64\lib\site-packages\construct\expr.py", line 188, in __call__
    return self.__parent(obj)[self.__field]
KeyError: 'found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 385, in sizeof
    return self._sizeof(context, "(sizeof)")
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2158, in _sizeof
    raise SizeofError("cannot calculate size, key not found in context", path=path)
construct.core.SizeofError: Error in path (sizeof)
cannot calculate size, key not found in context
```

What am I doing wrong?

Python 3.9.9 x64
Construct 2.10.67 (latest)

**Comment by arekbulski** [comment]
Oh but it does. Merry christmas.
```py3
In [17]: d = Struct(If(lambda this: this._.found, Byte))

In [18]: d.sizeof(found=1)
Out[18]: 1

In [19]: d = Struct(If(this._.found, Byte))

In [20]: d.sizeof(found=1)
Out[20]: 1
```

**Comment by theberrigan** [comment]
Thank you!

Now there is another problem.
Parsing works without _ but sizeof doesn't.
Parsing doesn't work with _ and sizeof works.
This happens with and without lambdas.

With _:
```py
from construct import Struct, Int16ul, Int32ul, Enum, If, this

Signature = Enum(
    Int16ul,
    V1 = 1,
    V2 = 2
)

MyStruct = Struct(
    'signature'  / Signature,
    'content'    / If(lambda this: this._.signature == Signature.V1, Int32ul),  # <-- used '_'
    # 'content'    / If(this._.signature == Signature.V1, Int32ul)
)

print(MyStruct.parse(b'\x01\x00\x11\x22\x33\x44'), '\n\n')  # <-- "KeyError: 'signature'"
print(MyStruct.sizeof(signature=Signature.V1))
```

Outputs:

```py
Traceback (most recent call last):
  File "C:\Python\39x64\lib\site-packages\construct\lib\containers.py", line 91, in __getattr__
    return self[name]
KeyError: 'signature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Berrigan\Desktop\test.py", line 15, in <module>
    print(MyStruct.parse(b'\x01\x00\x11\x22\x33\x44'), '\n\n')  # <-- "KeyError: 'signature'"
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2654, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 3851, in _parse
    condfunc = evaluate(self.condfunc, context)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 198, in evaluate
    return param(context) if callable(param) else param
  File "C:\Users\Berrigan\Desktop\test.py", line 11, in <lambda>
    'content'    / If(lambda this: this._.signature == Signature.V1, Int32ul),  # <-- used '_'
  File "C:\Python\39x64\lib\site-packages\construct\lib\containers.py", line 93, in __getattr__
    raise AttributeError(name)
AttributeError: signature
```

And without _:

```py
MyStruct = Struct(
    'signature'  / Signature,
    'content'    / If(lambda this: this.signature == Signature.V1, Int32ul),  # <-- without '_'
    # 'content'    / If(this.signature == Signature.V1, Int32ul)
)

print(MyStruct.parse(b'\x01\x00\x11\x22\x33\x44'), '\n\n')  # Ok
print(MyStruct.sizeof(signature=Signature.V1))              # <-- "KeyError: 'signature'"
```

Outputs:

```py
Container: 
    signature = (enum) V1 1
    content = 1144201745 


Traceback (most recent call last):
  File "C:\Python\39x64\lib\site-packages\construct\lib\containers.py", line 91, in __getattr__
    return self[name]
KeyError: 'signature'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2156, in _sizeof
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2156, in <genexpr>
    return sum(sc._sizeof(context, path) for sc in self.subcons)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2662, in _sizeof
    return self.subcon._sizeof(context, path)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 3861, in _sizeof
    condfunc = evaluate(self.condfunc, context)
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 198, in evaluate
    return param(context) if callable(param) else param
  File "C:\Users\Berrigan\Desktop\test.py", line 21, in <lambda>
    'content'    / If(lambda this: this.signature == Signature.V1, Int32ul),  # <-- without '_'
  File "C:\Python\39x64\lib\site-packages\construct\lib\containers.py", line 93, in __getattr__
    raise AttributeError(name)
AttributeError: signature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Berrigan\Desktop\test.py", line 26, in <module>
    print(MyStruct.sizeof(signature=Signature.V1))              # <-- "KeyError: 'signature'"
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 385, in sizeof
    return self._sizeof(context, "(sizeof)")
  File "C:\Python\39x64\lib\site-packages\construct\core.py", line 2158, in _sizeof
    raise SizeofError("cannot calculate size, key not found in context", path=path)
construct.core.SizeofError: Error in path (sizeof)
cannot calculate size, key not found in context
```

**Comment by arekbulski** [comment]
Sizeof is only fully supported on fixed sized instances, so no IFS or SWITCHES or anything. What you are doing steps outside of the practice. Note that you can do sizing without sizeof:
```py3
print(len(st.build(...)))
```

**Comment by theberrigan** [comment]
Aah, i got it, thanks a lot. Merry Christmas.
